package dev.richos.android.app

import android.app.Application
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.drawable.AdaptiveIconDrawable
import android.graphics.drawable.ColorDrawable
import androidx.test.core.app.ApplicationProvider
import dev.richos.android.R
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import java.io.File

/**
 * The launcher icon generated by `release/make-app-icon.cjs`, inflated and DRAWN the way a launcher
 * does (native graphics, no emulator): the manifest names it, all three adaptive layers inflate
 * (the themed-icon monochrome vector included), and the pixels land where the source puts them.
 *
 * Sample points are in the 1024 px source (`richos/app/icon-source/richos-icon-1024.png`), read
 * from its pixels: (260, 300) R ink #E7ECF4, (490, 400) gold arrow #D2B572, (560, 760) the dark
 * body #151D2F, (60, 512) outside the body, transparent. The generator draws the 1024 canvas at
 * [CANVAS_DP] of the 108 dp layer; a launcher shows the middle 72 dp.
 *
 * With RICHOS_SHOTS set, the renders are written there as PNGs for a person to look at.
 */
@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(sdk = [35], application = Application::class)
class LauncherIconTest {
    private val context: Application = ApplicationProvider.getApplicationContext()

    @Test
    fun `the manifest names the adaptive icon, and its round twin is adaptive too`() {
        assertEquals(R.mipmap.ic_launcher, context.applicationInfo.icon)
        // ApplicationInfo's round-icon field is hidden API; the resource itself must inflate.
        assertTrue(context.getDrawable(R.mipmap.ic_launcher_round) is AdaptiveIconDrawable)
    }

    @Test
    fun `the full icon draws the RichOS body on the ground, masked`() {
        val icon = adaptive()
        val bitmap = render(icon, SIZE)
        save(bitmap, "launcher-icon.png")
        // The visible 72 dp spans the bitmap; the source canvas spans CANVAS_DP of it.
        fun at(x: Int, y: Int) = bitmap.getPixel(visible(x), visible(y))
        assertLight("R ink", at(260, 300))
        assertGold("arrow", at(490, 400))
        assertDark("body", at(560, 760))
        // Outside the body, inside the mask: the background layer, the app ground #0C1322.
        assertEquals("ground", 0xFF0C1322.toInt(), at(60, 512))
        // The bitmap's corner lies outside every launcher mask shape.
        assertEquals("masked corner", 0, Color.alpha(bitmap.getPixel(1, 1)))
    }

    @Test
    fun `the themed monochrome layer is the R with the arrow cut out`() {
        val mono = adaptive().monochrome!!
        val bitmap = render(mono, SIZE)
        fun alpha(x: Int, y: Int) = Color.alpha(bitmap.getPixel(layer(x), layer(y)))
        assertEquals("R ink is solid", 255, alpha(260, 300))
        assertEquals("R leg is solid", 255, alpha(760, 800))
        assertEquals("the arrow is cut out of the R", 0, alpha(490, 400))
        assertEquals("the body around the R is clear", 0, alpha(560, 760))
        assertEquals("outside the body is clear", 0, alpha(60, 512))
        // What a themed launcher shows: the layer tinted one color on a themed ground.
        val themed = AdaptiveIconDrawable(ColorDrawable(0xFFD8E2FF.toInt()), mono.mutate().apply { setTint(0xFF00315B.toInt()) })
        save(render(themed, SIZE), "launcher-icon-themed.png")
    }

    private fun adaptive(): AdaptiveIconDrawable {
        val drawable = context.getDrawable(R.mipmap.ic_launcher)
        assertTrue("ic_launcher is an adaptive icon, got $drawable", drawable is AdaptiveIconDrawable)
        val icon = drawable as AdaptiveIconDrawable
        assertNotNull("background layer", icon.background)
        assertNotNull("foreground layer", icon.foreground)
        assertNotNull("monochrome layer", icon.monochrome)
        return icon
    }

    private fun render(drawable: android.graphics.drawable.Drawable, size: Int): Bitmap {
        val bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888)
        drawable.setBounds(0, 0, size, size)
        drawable.draw(Canvas(bitmap))
        return bitmap
    }

    /** Source px to bitmap px when the bitmap is the launcher's visible 72 dp. */
    private fun visible(source: Int) = (SIZE / 2.0 + (source - 512) * (CANVAS_DP / 72.0) * SIZE / 1024.0).toInt()

    /** Source px to bitmap px when the bitmap is the whole 108 dp layer. */
    private fun layer(source: Int) = (SIZE / 2.0 + (source - 512) * (CANVAS_DP / 108.0) * SIZE / 1024.0).toInt()

    private fun luminance(c: Int) = (Color.red(c) * 299 + Color.green(c) * 587 + Color.blue(c) * 114) / 1000

    private fun assertLight(what: String, c: Int) =
        assertTrue("$what should be light, got #${Integer.toHexString(c)}", luminance(c) > 200)

    private fun assertDark(what: String, c: Int) =
        assertTrue("$what should be dark, got #${Integer.toHexString(c)}", luminance(c) < 60)

    private fun assertGold(what: String, c: Int) =
        assertTrue("$what should be gold, got #${Integer.toHexString(c)}", Color.red(c) - Color.blue(c) > 60 && luminance(c) > 120)

    private fun save(bitmap: Bitmap, name: String) {
        val dir = System.getenv("RICHOS_SHOTS")?.takeIf { it.isNotBlank() } ?: return
        File(dir).mkdirs()
        File(dir, name).outputStream().use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
    }

    private companion object {
        /** 432 px: the xxxhdpi size of the 108 dp layer, and of the visible 72 dp at 6x. */
        const val SIZE = 432

        /** The 1024 canvas in dp, as release/make-app-icon.cjs derives it: 33 * 1024 / 510.66. */
        const val CANVAS_DP = 66.17
    }
}
