#!/usr/bin/env bash
#
# guard-publication-writes.sh — PreToolUse guard (Write|Edit|MultiEdit|NotebookEdit).
#
# REFUSES to write private material into a repository that declares itself
# publication-bound. Same hook shape as scan-secrets.sh, same matcher, a
# different predicate: that one asks "is this a credential?", this one asks
# "is this something a person said in private?".
#
# The full rationale, the two detectors, the measured precision and the honest
# list of what this cannot catch all live in scripts/lib/publication-boundary.sh
# — one place, because the commit-time half (guard-publication-commits.sh) runs
# the identical predicate and a predicate in two copies is the exact defect
# class this mechanism exists to end.
#
# WHY A WRITE HOOK IS NOT ENOUGH, AND WHAT COVERS THE REST:
# this catches content an agent authors in THIS session. It cannot see a file
# arriving by `git mv`, by `cp`, from an editor, or — the case that actually
# happened — generated by a tool (137 of the 2026-08-29 asset files were
# whisper output, and no Write tool ever touched them). guard-publication-
# commits.sh closes that by re-running the same predicate against the staged
# INDEX, where provenance stops mattering.
#
# FAIL-CLOSED on a missing python3 and on a broken declaration. FAILS OPEN
# (exit 0) on a malformed/unparseable hook payload, matching its two siblings
# on this same matcher (guard-main-checkout-writes.sh, scan-secrets.sh): a
# payload that cannot be understood is not itself a disclosure.

set -eo pipefail

command -v python3 >/dev/null 2>&1 || { echo "ERROR: guard-publication-writes.sh: python3 is required for payload parsing — refusing (fail-closed)" >&2; exit 2; }

# --- ROOT RESOLUTION -------------------------------------------------------
# TWO ROOTS, NEVER ONE. The full contract, and why the old single-root
# resolution was wrong the moment the engine became loadable by reference,
# is in scripts/lib/resolve-roots.sh. This bootstrap block is byte-identical
# in every hook that needs a root; contract-integrity-probe.sh Layer R asserts
# that, so a divergent copy is a probe failure rather than a surprise.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_RR_LIB="$SCRIPT_DIR/../lib/resolve-roots.sh"
if [ ! -f "$_RR_LIB" ]; then
    {
        echo "=== RICHOS ENGINE: BROKEN INSTALL — ENFORCEMENT IS NOT ACTIVE ==="
        echo "  hook: scripts/hooks/guard-publication-writes.sh"
        echo "  scripts/lib/resolve-roots.sh is missing at: $_RR_LIB"
        echo "  Without it this guard cannot tell WHICH REPOSITORY it governs."
        echo "  It will not guess, and it will not carry on quietly — a defense"
        echo "  that reports 'on' while protecting nothing is worse than none."
    } >&2
    exit 2
fi
# shellcheck source=../lib/resolve-roots.sh
. "$_RR_LIB"
ENGINE_ROOT="$(resolve_engine_root "$SCRIPT_DIR")"

# --- JURISDICTION ----------------------------------------------------------
# Deliberately BELOW the root-resolution bootstrap, never inside it: Layer R of
# contract-integrity-probe.sh extracts that block verbatim and asserts it is
# byte-identical across every rooted hook, so anything added inside it would
# read as divergence.
#
# The seat resolved above answers "am I governed?". It does NOT answer "does
# the artifact I was just handed belong to the repository I govern?" — and
# until 2026-08-30 nothing asked. See scripts/lib/seat-jurisdiction.sh.
_SJ_LIB="$SCRIPT_DIR/../lib/seat-jurisdiction.sh"
if [ ! -f "$_SJ_LIB" ]; then
    {
        echo "=== RICHOS ENGINE: BROKEN INSTALL — ENFORCEMENT IS NOT ACTIVE ==="
        echo "  hook: scripts/hooks/guard-publication-writes.sh"
        echo "  scripts/lib/seat-jurisdiction.sh is missing at: $_SJ_LIB"
        echo "  Without it this guard cannot tell whether the artifact it was"
        echo "  handed belongs to the repository it governs, and a guard that"
        echo "  cannot tell must not answer."
    } >&2
    exit 2
fi
# shellcheck source=../lib/seat-jurisdiction.sh
. "$_SJ_LIB"

INPUT="$(cat)"

if resolve_entity_root "$INPUT"; then
    # CAPTURED, not discarded. This used to be `:` — the seat decided whether
    # this guard ran and then had no say in WHAT it judged, which is the
    # divergence in its purest form.
    SEAT_ROOT="$RICHOS_ENTITY_ROOT_RESOLVED"
elif [ "$RICHOS_ROOT_STATUS" = "not-adopted" ]; then
    # DELIBERATELY NOT AN EXIT. This guard reads its contract out of the TARGET
    # repository, not out of the seat, so an unadopted seat is not a reason to
    # stop — the artifact's own repository still gets to govern itself below
    # by its own declaration. Exiting here is what made a committed
    # .publication-boundary readable by nothing at all.
    SEAT_ROOT=""
else
    root_failure_banner "scripts/hooks/guard-publication-writes.sh" >&2
    exit 2
fi

_PB_LIB="$SCRIPT_DIR/../lib/publication-boundary.sh"
if [ ! -f "$_PB_LIB" ]; then
    {
        echo "=== RICHOS ENGINE: BROKEN INSTALL — ENFORCEMENT IS NOT ACTIVE ==="
        echo "  hook: scripts/hooks/guard-publication-writes.sh"
        echo "  scripts/lib/publication-boundary.sh is missing at: $_PB_LIB"
        echo "  This guard's entire predicate lives there. Without it it cannot"
        echo "  tell private material from ordinary work, and it will not guess."
    } >&2
    exit 2
fi
# shellcheck source=../lib/publication-boundary.sh
. "$_PB_LIB"

TOOL_NAME="$(printf '%s' "$INPUT" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("tool_name",""))' 2>/dev/null || true)"
case "$TOOL_NAME" in
  Write|Edit|MultiEdit|NotebookEdit) ;;
  *) exit 0 ;;
esac

FILE_PATH="$(printf '%s' "$INPUT" | python3 -c 'import json,sys; d=json.load(sys.stdin); ti=d.get("tool_input",{}) or {}; print(ti.get("file_path") or ti.get("notebook_path") or "")' 2>/dev/null || true)"
[ -n "$FILE_PATH" ] || exit 0
case "$FILE_PATH" in
  /*) ;;
  *) exit 0 ;;   # a relative path has no unambiguous repository; the commit guard still sees it
esac

# --- SCOPE: which repository, and is this path publication-bound? -----------
# Physicalized once, here, so every later comparison (repo containment, the
# ALLOWLIST prefix test, check-ignore) is asking about the same path. See
# pb_physical for the /var-vs-/private/var failure this prevents.
FILE_PATH="$(pb_physical "$FILE_PATH")"
PB_REPO="$(pb_repo_root "$FILE_PATH" 2>/dev/null || true)"
[ -n "$PB_REPO" ] || exit 0

# --- GOVERNANCE: the artifact's OWN repository decides ---------------------
# "Am I governed?" and "what am I inspecting?" are the same question here, and
# they are now asked of the SAME repository: the declaration loaded immediately
# below is read out of $FILE_PATH — which is also the thing being judged. Two
# questions about one repository cannot disagree; that is the whole fix, and it
# needs no extra comparison to hold.
#
# The seat is deliberately given NO VETO. It used to have one: an unadopted seat
# exited before this point, which is exactly why richos-hq's committed
# .row-currency and .ceo-todos were read by nothing at all while the repository
# took 28 commits in a day. The seat is REPORTED when it differs from the
# artifact's repository, and never obeyed — a guard that switched itself off on
# a seat mismatch would have let through a merge that was correctly refused.
if [ -n "${SEAT_ROOT}" ]; then
    richos_assert_jurisdiction "scripts/hooks/guard-publication-writes.sh" "${SEAT_ROOT}" "$FILE_PATH" "file" "proceeds" || true
fi

# `set -e` would abort on a bare non-zero return here, taking the rc 1
# "no declaration, stand down" branch with it — so the status is captured
# through `||` and then dispatched.
PB_DECL_RC=0
pb_load_declaration "$PB_REPO" || PB_DECL_RC=$?
case "$PB_DECL_RC" in
  0) ;;
  1) exit 0 ;;   # this repository declares no publication boundary — nothing to enforce
  *) pb_broken_banner "guard-publication-writes.sh" "$PB_BROKEN_REASON" >&2; exit 2 ;;
esac

# ALLOWLIST FIRST, and it is now checked before the gitignore allowance rather
# than after it. It is the one sanctioned way through this mechanism, it is
# committed and reviewable, and it exempts a path from EVERY detector including
# identity — so it cannot sit downstream of a branch that exits before it.
if pb_allowlisted "$PB_REPO" "$FILE_PATH"; then
    exit 0
fi

# A gitignored destination is NOT publication-bound. Private material belongs
# there — it is how the source audio was handled correctly all along — so this
# is an allow, not a grudging exception.
#
# WITH ONE EXCEPTION, AND IT IS THE WHOLE POINT OF PRIVATE_FILES: a file
# declared private by identity has ONE home, named in the declaration, and this
# repository is not it in any form. "Never enters this repository" that stopped
# at .gitignore would be a rule about publication when the instruction was about
# the file. So an ignored destination downgrades to an IDENTITY-ONLY scan
# instead of exiting: no corpus is built, nothing is judged by resemblance, and
# with no PRIVATE_FILES declared this branch is byte-for-byte the old behavior.
PB_IDENTITY_ONLY=0
if pb_path_is_ignored "$PB_REPO" "$FILE_PATH"; then
    [ -n "$PB_PRIVATE_FILES" ] || exit 0
    PB_IDENTITY_ONLY=1
fi

PB_SOURCES_OK=""
PB_SOURCES_SKIPPED=""
if [ "$PB_IDENTITY_ONLY" = "0" ]; then
    if ! pb_resolve_sources "$PB_REPO"; then
        pb_broken_banner "guard-publication-writes.sh" "$PB_BROKEN_REASON" >&2
        exit 2
    fi
fi

# --- The new text this call would introduce ---------------------------------
# Write: content. Edit: new_string. MultiEdit: every edits[].new_string.
# NotebookEdit: new_source. Identical extraction to scan-secrets.sh, for the
# identical reason: the OLD text is already on disk and was already judged.
JOB="$(mktemp -t pub-boundary-job.XXXXXX.json)"
trap 'rm -f "$JOB"' EXIT

PB_SOURCES_JSON="$(printf '%s' "$PB_SOURCES_OK" | python3 -c '
import json, sys
raw = sys.stdin.read()
print(json.dumps([s for s in raw.split("\t") if s]))
' 2>/dev/null || printf '[]')"

printf '%s' "$INPUT" | PB_LABEL="$FILE_PATH" PB_JOB="$JOB" \
    PB_MIN_SPEECH="$PB_MIN_SPEECH_LINES" PB_MIN_QUOTE="$PB_MIN_QUOTE_WORDS" \
    PB_MAX_FILES="$PB_CORPUS_MAX_FILES" PB_MAX_BYTES="$PB_CORPUS_MAX_BYTES" \
    PB_MAY_BE_EMPTY="$PB_CORPUS_MAY_BE_EMPTY" \
    PB_SOURCES="$PB_SOURCES_JSON" \
    PB_PRIVATE_FILES="$PB_PRIVATE_FILES" PB_IDENTITY_ONLY="$PB_IDENTITY_ONLY" \
    python3 -c '
import json, os, sys
try:
    payload = json.load(sys.stdin)
except Exception:
    payload = {}
ti = payload.get("tool_input", {}) or {}
tool = payload.get("tool_name", "")
texts = []
if tool == "Write":
    texts.append(ti.get("content") or "")
elif tool == "Edit":
    texts.append(ti.get("new_string") or "")
elif tool == "MultiEdit":
    for e in (ti.get("edits") or []):
        if isinstance(e, dict):
            texts.append(e.get("new_string") or "")
elif tool == "NotebookEdit":
    texts.append(ti.get("new_source") or "")
item = {"label": os.environ.get("PB_LABEL", "<file>"),
        "text": "\n".join(t for t in texts if isinstance(t, str))}
if os.environ.get("PB_IDENTITY_ONLY") == "1":
    item["identity_only"] = True
job = {
    "min_speech_lines": int(os.environ.get("PB_MIN_SPEECH", "8")),
    "min_quote_words": int(os.environ.get("PB_MIN_QUOTE", "10")),
    "corpus_max_files": int(os.environ.get("PB_MAX_FILES", "4000")),
    "corpus_max_bytes": int(os.environ.get("PB_MAX_BYTES", "67108864")),
    "corpus_may_be_empty": os.environ.get("PB_MAY_BE_EMPTY", "0") == "1",
    "sources": json.loads(os.environ.get("PB_SOURCES", "[]")),
    "private_files": (os.environ.get("PB_PRIVATE_FILES", "") or "").split(),
    "items": [item],
}
with open(os.environ["PB_JOB"], "w", encoding="utf-8") as fh:
    json.dump(job, fh)
' || { echo "ERROR: guard-publication-writes.sh: could not build the scan job — refusing (fail-closed)" >&2; exit 2; }

RESULT="$(pb_scan "$JOB" || true)"

case "$(printf '%s' "$RESULT" | head -1 | cut -f1)" in
  CLEAN)
    exit 0 ;;
  BROKEN)
    pb_broken_banner "guard-publication-writes.sh" "$(printf '%s' "$RESULT" | head -1 | cut -f2-)" >&2
    exit 2 ;;
  BLOCK)
    pb_refusal "guard-publication-writes.sh" \
        "Refusing to write '$FILE_PATH'." \
        "$RESULT" "$PB_REPO" "$PB_SOURCES_SKIPPED" >&2
    exit 2 ;;
  *)
    echo "ERROR: guard-publication-writes.sh: unexpected scanner output — refusing (fail-closed)" >&2
    exit 2 ;;
esac
