// Android push through the Connect Worker: the FCM HTTP v1 sender against a fake Google (OAuth token
// endpoint + FCM send endpoint), dispatch by registration platform through the real signed handler
// and SQLite schema, the schema-3 migration of a live schema-2 database, and the deployment artifact.
// A fake endpoint proves our requests and our handling of Google's answers, never device delivery.
const test = require('node:test'), assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const { DatabaseSync } = require('node:sqlite');
const { fixture } = require('./connect-fixture.cjs');

const PROJECT = 'richos-fixture', APP = 'dev.richos.android.fixture';
// PEM armor is assembled at run time: every key here is generated by the test and discarded.
const pem = (label, bytes) => { const dashes = '-'.repeat(5);
  return `${dashes}BEGIN ${label}${dashes}\n${Buffer.from(bytes).toString('base64').match(/.{1,64}/g).join('\n')}\n${dashes}END ${label}${dashes}\n`; };

// A real RSA service-account key, a fake Google that verifies every assertion with its public half,
// and a scripted answer queue for the send endpoint.
async function google({ now }) {
  const keys = await crypto.subtle.generateKey({ name: 'RSASSA-PKCS1-v1_5', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' }, true, ['sign', 'verify']);
  const privateKey = pem('PRIVATE KEY', await crypto.subtle.exportKey('pkcs8', keys.privateKey));
  const serviceAccount = JSON.stringify({ type: 'service_account', project_id: PROJECT, private_key_id: 'f'.repeat(40), private_key: privateKey,
    client_email: `push@${PROJECT}.iam.gserviceaccount.com`, client_id: '1'.repeat(21), token_uri: 'https://oauth2.googleapis.com/token' });
  const state = { oauth: [], sends: [], answers: [], oauthAnswers: [], issued: 0, requests: [] };
  async function fetchImpl(url, options) {
    state.requests.push({ url, options });
    assert.equal(options.redirect, 'manual'); assert(options.signal instanceof AbortSignal);
    if (url === 'https://oauth2.googleapis.com/token') {
      const form = new URLSearchParams(options.body);
      assert.equal(options.method, 'POST'); assert.equal(options.headers['content-type'], 'application/x-www-form-urlencoded');
      assert.equal(form.get('grant_type'), 'urn:ietf:params:oauth:grant-type:jwt-bearer');
      const [header, claims, signature] = form.get('assertion').split('.');
      assert(await crypto.subtle.verify('RSASSA-PKCS1-v1_5', keys.publicKey, Buffer.from(signature, 'base64url'), Buffer.from(header + '.' + claims)), 'assertion is signed by the service-account key');
      state.oauth.push({ header: JSON.parse(Buffer.from(header, 'base64url')), claims: JSON.parse(Buffer.from(claims, 'base64url')) });
      const answer = state.oauthAnswers.shift();
      if (answer instanceof Error) throw answer;
      if (answer) return answer;
      return Response.json({ access_token: `ya29.fixture-${++state.issued}`, expires_in: 3599, token_type: 'Bearer' });
    }
    assert.equal(url, `https://fcm.googleapis.com/v1/projects/${PROJECT}/messages:send`);
    state.sends.push({ authorization: options.headers.authorization, body: JSON.parse(options.body) });
    const answer = state.answers.shift();
    if (answer instanceof Error) throw answer;
    return answer || Response.json({ name: `projects/${PROJECT}/messages/0:1` });
  }
  const env = { FCM_SERVICE_ACCOUNT: serviceAccount, FCM_PROJECT_ID: PROJECT, FCM_APPS: APP };
  return { keys, privateKey, serviceAccount, env, state, fetchImpl };
}
const fcmError = (status, errorCode, extra = []) => Response.json({ error: { code: status, status: 'X',
  details: [{ '@type': 'type.googleapis.com/google.firebase.fcm.v1.FcmError', errorCode }, ...extra] } }, { status });
const binding = { host_id: 'a'.repeat(32), token: 'fixture-token_' + 'x'.repeat(140) + ':APA91b', topic: APP, platform: 'fcm' };
const job = (at, extra = {}) => ({ event_ref: 'b'.repeat(64), thread_ref: 'c'.repeat(64), expires_at: at + 3600000, ...extra });

test('FCM signs an RS256 service-account assertion, caches the access token and sends a data-only high-priority message', async () => {
  const { FCM } = await import('../service/connect/fcm.mjs');
  let time = 1790000000000; const g = await google({ now: () => time });
  const fcm = new FCM(g.env, { fetchImpl: g.fetchImpl, now: () => time });
  const preview = JSON.stringify({ v: 1, nonce: 'a'.repeat(16), body: 'b'.repeat(100) });
  assert.deepEqual(await fcm.send(binding, job(time, { preview })), { outcome: 'sent' });
  const [{ header, claims }] = g.state.oauth;
  assert.deepEqual(header, { alg: 'RS256', typ: 'JWT', kid: 'f'.repeat(40) });
  assert.deepEqual(claims, { iss: `push@${PROJECT}.iam.gserviceaccount.com`, scope: 'https://www.googleapis.com/auth/firebase.messaging',
    aud: 'https://oauth2.googleapis.com/token', iat: 1790000000, exp: 1790003600 });
  const [send] = g.state.sends;
  assert.equal(send.authorization, 'Bearer ya29.fixture-1');
  assert.deepEqual(send.body, { message: { token: binding.token,
    data: { v: '1', host: binding.host_id, thread: 'c'.repeat(64), event: 'b'.repeat(64), preview },
    android: { priority: 'HIGH', ttl: '3600s', collapse_key: 'b'.repeat(64), restricted_package_name: APP } } });
  assert(!('notification' in send.body.message) && !('notification' in send.body.message.android), 'no visible text crosses Google');
  assert(Object.values(send.body.message.data).every(value => typeof value === 'string'), 'FCM data values are strings');
  // The access token is reused until five minutes before expiry, then a fresh assertion is signed.
  time += 3000 * 1000; await fcm.send(binding, job(time));
  assert.equal(g.state.oauth.length, 1); assert.equal(g.state.sends[1].authorization, 'Bearer ya29.fixture-1');
  assert.equal(g.state.sends[1].body.message.data.preview, undefined, 'no preview field without ciphertext');
  // The Worker builds a sender per request; the token outlives the instance.
  await new FCM(g.env, { fetchImpl: g.fetchImpl, now: () => time }).send(binding, job(time));
  assert.equal(g.state.oauth.length, 1, 'a new sender for the same secret reuses the access token');
  time += 400 * 1000; await fcm.send(binding, job(time - 3590 * 1000));
  assert.equal(g.state.oauth.length, 2); assert.equal(g.state.sends[3].authorization, 'Bearer ya29.fixture-2');
  assert.equal(g.state.sends[3].body.message.android.ttl, '10s', 'the TTL is the job\'s remaining lifetime');
  // No key material in any request.
  const keyLine = g.privateKey.split('\n')[1];
  for (const request of g.state.requests) assert(!String(request.options.body).includes(keyLine));
});

test('FCM maps Google\'s answers onto the APNs outcomes: invalid, retry and configuration', async () => {
  const { FCM } = await import('../service/connect/fcm.mjs');
  const time = 1790000000000, g = await google({ now: () => time });
  const fcm = new FCM(g.env, { fetchImpl: g.fetchImpl, now: () => time });
  const badToken = { '@type': 'type.googleapis.com/google.rpc.BadRequest', fieldViolations: [{ field: 'message.token', description: 'Invalid registration token' }] };
  const cases = [
    [fcmError(404, 'UNREGISTERED'), { outcome: 'invalid' }],
    [fcmError(403, 'SENDER_ID_MISMATCH'), { outcome: 'invalid' }],
    [fcmError(400, 'INVALID_ARGUMENT', [badToken]), { outcome: 'invalid' }],
    // A bad request that does not name the token is our fault: the phone keeps its registration.
    [fcmError(400, 'INVALID_ARGUMENT', [{ '@type': 'type.googleapis.com/google.rpc.BadRequest', fieldViolations: [{ field: 'message.data' }] }]), { outcome: 'configuration', code: 'http_400' }],
    [fcmError(403, 'PERMISSION_DENIED'), { outcome: 'configuration', code: 'http_403' }],
    [fcmError(429, 'QUOTA_EXCEEDED'), { outcome: 'retry', code: 'http_429' }],
    [fcmError(503, 'UNAVAILABLE'), { outcome: 'retry', code: 'http_503' }],
    [fcmError(500, 'INTERNAL'), { outcome: 'retry', code: 'http_500' }],
    [new Response('not json', { status: 502 }), { outcome: 'retry', code: 'http_502' }],
    [Object.assign(Error('timed out'), { name: 'TimeoutError' }), { outcome: 'retry', code: 'timeout' }],
    [new TypeError('network'), { outcome: 'retry', code: 'transport' }],
  ];
  for (const [answer, expected] of cases) { g.state.answers.push(answer); assert.deepEqual(await fcm.send(binding, job(time)), expected, JSON.stringify(expected)); }
  // A rejected access token is dropped, so the next attempt signs a new assertion.
  const before = g.state.oauth.length;
  g.state.answers.push(fcmError(401, 'UNAUTHENTICATED'));
  assert.deepEqual(await fcm.send(binding, job(time)), { outcome: 'retry', code: 'http_401' });
  await fcm.send(binding, job(time)); assert.equal(g.state.oauth.length, before + 1);
});

test('FCM refuses to send without a matching configuration and classifies OAuth failures', async () => {
  const { FCM, configuredFcm } = await import('../service/connect/fcm.mjs');
  const time = 1790000000000, g = await google({ now: () => time });
  const account = JSON.parse(g.serviceAccount);
  for (const env of [{}, { ...g.env, FCM_PROJECT_ID: 'other-project' }, { ...g.env, FCM_APPS: 'dev.richos.other' }, { ...g.env, FCM_SERVICE_ACCOUNT: 'not json' },
    { ...g.env, FCM_SERVICE_ACCOUNT: JSON.stringify({ ...account, type: 'authorized_user' }) }, { ...g.env, FCM_SERVICE_ACCOUNT: JSON.stringify({ ...account, private_key: '' }) }]) {
    assert.equal(configuredFcm(env, binding), false);
    const fcm = new FCM(env, { fetchImpl: g.fetchImpl, now: () => time });
    assert.deepEqual(await fcm.send(binding, job(time)), { outcome: 'configuration' });
  }
  assert.equal(configuredFcm(g.env, { ...binding, topic: 'not-an-app-id' }), false);
  assert.equal(g.state.requests.length, 0, 'nothing reaches Google without configuration');
  const fcm = new FCM(g.env, { fetchImpl: g.fetchImpl, now: () => time });
  g.state.oauthAnswers.push(Response.json({ error: 'invalid_grant' }, { status: 400 }));
  assert.deepEqual(await fcm.send(binding, job(time)), { outcome: 'configuration', code: 'oauth_http_400' });
  g.state.oauthAnswers.push(new Response('', { status: 503 }));
  assert.deepEqual(await fcm.send(binding, job(time)), { outcome: 'retry', code: 'oauth_http_503' });
  g.state.oauthAnswers.push(new TypeError('network'));
  assert.deepEqual(await fcm.send(binding, job(time)), { outcome: 'retry', code: 'oauth_transport' });
  assert.equal(g.state.sends.length, 0, 'no send without an access token');
  const unsigned = new FCM({ ...g.env, FCM_SERVICE_ACCOUNT: JSON.stringify({ ...account, private_key: pem('PRIVATE KEY', new Uint8Array(3)) }) }, { fetchImpl: g.fetchImpl, now: () => time });
  assert.deepEqual(await unsigned.send(binding, job(time)), { outcome: 'configuration', code: 'signing' });
});

test('default FCM transport calls global fetch with its native receiver', async () => {
  const { FCM } = await import('../service/connect/fcm.mjs');
  const g = await google({ now: Date.now }), original = globalThis.fetch;
  try {
    globalThis.fetch = function () { assert.equal(this, globalThis, 'Worker fetch must not receive the FCM adapter as its receiver'); return Promise.resolve(fcmError(404, 'UNREGISTERED')); };
    const fcm = new FCM(g.env); fcm.token = async () => 'signed-fixture';
    assert.equal((await fcm.send(binding, job(Date.now()))).outcome, 'invalid');
  } finally { globalThis.fetch = original; }
});

// The real signed handler, real SQLite schema, real FCM class against the fake Google, and a
// recording APNs sender: every job must go to exactly one provider, the registration's.
async function service(t, { route = 'tailnet' } = {}) {
  const f = await fixture(t), { handle, reconcile } = await import('../service/connect-worker.mjs'), { FCM } = await import('../service/connect/fcm.mjs');
  const g = await google({ now: () => f.store.now() });
  Object.assign(f.env, g.env, { APNS_TEAM_ID: 'A123456789', APNS_SANDBOX_KEY_ID: 'B123456789', APNS_SANDBOX_KEY: 'server-secret', APNS_TOPICS: 'dev.richos.mobile.integration' });
  const apnsCalls = []; let apnsOutcome = 'sent';
  const ports = { store: f.store, provider: f.provider, now: () => f.store.now(),
    apns: { send: async (b, j) => { apnsCalls.push({ binding: b, job: j }); return { outcome: apnsOutcome }; } },
    fcm: new FCM(f.env, { fetchImpl: g.fetchImpl, now: () => f.store.now() }) };
  const id = await f.identity();
  const call = (method, path, data) => id.request(method, path, data === undefined ? '' : JSON.stringify(data)).then(request => handle(request, f.env, ports));
  assert.equal((await call('POST', route === 'connect' ? '/v1/hosts' : '/v1/push/hosts')).status, 200);
  const deviceHash = 'a'.repeat(64);
  if (route === 'connect') assert.equal((await call('PUT', '/v1/host/device', { generation: 1, deviceKeyHash: deviceHash })).status, 200);
  const android = { revision: 1, generation: 1, deviceHash, token: binding.token, platform: 'fcm', topic: APP, route };
  const iphone = { revision: 1, generation: 1, deviceHash, token: 'd'.repeat(64), topic: 'dev.richos.mobile.integration', environment: 'sandbox', route };
  const event = { eventRef: 'b'.repeat(64), threadRef: 'c'.repeat(64), revision: 1, deviceHash };
  const row = () => f.store.statement('SELECT * FROM push_bindings WHERE host_id=?', id.id).first();
  const jobs = async () => (await f.store.statement('SELECT * FROM push_jobs WHERE host_id=?', id.id).all()).results;
  return { ...f, g, id, call, android, iphone, event, row, jobs, apnsCalls, apnsOutcome: value => { apnsOutcome = value; }, reconcile: () => reconcile(f.env, ports) };
}

test('an APNs registration without a platform field is stored as APNs and is never sent through FCM', async t => {
  const s = await service(t);
  assert.equal((await s.call('PUT', '/v1/push/device', s.iphone)).status, 200);
  assert.equal((await s.row()).platform, 'apns');
  assert.equal((await s.call('PUT', '/v1/push/device', { ...s.iphone, platform: 'apns' })).status, 200, 'the explicit spelling is the same registration');
  assert.equal((await s.call('POST', '/v1/push/events', s.event)).status, 202);
  assert.equal(s.apnsCalls.length, 1); assert.equal(s.g.state.requests.length, 0);
});

test('an FCM registration is delivered through FCM with ciphertext only, and never through APNs', async t => {
  for (const route of ['tailnet', 'connect']) await t.test(route, async t => {
    const s = await service(t, { route });
    assert.equal((await s.call('PUT', '/v1/push/device', s.android)).status, 200);
    const stored = await s.row();
    assert.equal(stored.platform, 'fcm'); assert.equal(stored.environment, null); assert.equal(stored.topic, APP);
    const preview = { v: 1, nonce: 'a'.repeat(16), body: 'b'.repeat(100) };
    const response = await s.call('POST', '/v1/push/events', { ...s.event, preview });
    assert.equal(response.status, 202); assert.deepEqual(await response.json(), { accepted: true, delivery: { outcome: 'sent' } });
    assert.equal(s.apnsCalls.length, 0);
    const [send] = s.g.state.sends;
    assert.deepEqual(send.body.message.data, { v: '1', host: s.id.id, thread: 'c'.repeat(64), event: 'b'.repeat(64), preview: JSON.stringify(preview) });
    assert.equal(send.body.message.android.restricted_package_name, APP);
    assert.equal(send.body.message.android.ttl, '3600s');
    // The same event is deduplicated exactly as for APNs.
    assert.equal((await s.call('POST', '/v1/push/events', { ...s.event, preview })).status, 202);
    assert.equal(s.g.state.sends.length, 1);
  });
});

test('FCM registrations with the wrong shape or no server configuration are refused and store nothing', async t => {
  const s = await service(t);
  const refused = [
    { ...s.android, environment: 'production' },
    { ...s.android, token: 'has/slash' + 'x'.repeat(60) },
    { ...s.android, token: 'short' },
    { ...s.android, topic: 'dev.richos.other' },
    { ...s.android, topic: 'dev.richos.mobile.integration' },
    { ...s.android, platform: 'gcm' },
    { ...s.android, platform: null },
    { ...s.iphone, platform: 'fcm' },
    { ...s.android, platform: 'apns' },
    { ...s.android, extra: true },
  ];
  for (const body of refused) assert.equal((await s.call('PUT', '/v1/push/device', body)).status, 400, JSON.stringify(body));
  for (const name of ['FCM_SERVICE_ACCOUNT', 'FCM_PROJECT_ID', 'FCM_APPS']) {
    const saved = s.env[name]; delete s.env[name];
    assert.equal((await s.call('PUT', '/v1/push/device', s.android)).status, 400, `missing ${name}`);
    s.env[name] = saved;
  }
  assert.equal(await s.row(), null);
  assert.equal((await s.call('PUT', '/v1/push/device', s.android)).status, 200);
});

test('an unregistered FCM token is deleted with its pending jobs; an FCM request error keeps it', async t => {
  for (const [answer, invalid] of [[fcmError(404, 'UNREGISTERED'), true], [fcmError(403, 'SENDER_ID_MISMATCH'), true], [fcmError(400, 'INVALID_ARGUMENT'), false]]) {
    await t.test(`${answer.status} ${invalid ? 'invalid' : 'kept'}`, async t => {
      const s = await service(t);
      await s.call('PUT', '/v1/push/device', s.android);
      s.g.state.answers.push(answer);
      assert.equal((await s.call('POST', '/v1/push/events', s.event)).status, 202);
      const row = await s.row();
      assert.equal(row.token, invalid ? null : s.android.token);
      assert.equal((await s.jobs()).length, invalid ? 0 : 1);
      if (invalid) assert.equal((await s.call('POST', '/v1/push/events', s.event)).status, 409, 'no delivery authority after invalidation');
      else assert.equal((await s.jobs())[0].state, 'failed', 'a configuration failure is not retried');
    });
  }
});

test('FCM retries follow the APNs job semantics: bounded attempts, backoff and one-hour expiry', async t => {
  const s = await service(t);
  await s.call('PUT', '/v1/push/device', s.android);
  for (let n = 0; n < 10; n++) s.g.state.answers.push(fcmError(503, 'UNAVAILABLE'));
  await s.call('POST', '/v1/push/events', s.event);
  // The shared backoff is 2, 4, 8, then 15 minutes: attempts at minutes 0, 5, 10, 20 and 35 on a
  // five-minute scheduler, and never a sixth.
  const sent = [];
  for (let n = 0; n < 11; n++) { s.advance(300000); await s.reconcile(); sent.push(s.g.state.sends.length); }
  assert.deepEqual(sent, [2, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5], 'backoff schedule and at most five attempts');
  assert.equal((await s.jobs())[0].state, 'failed');
  s.advance(3600000); await s.reconcile();
  assert.equal((await s.jobs()).length, 0, 'jobs expire after one hour');
  // A pending job that reaches its expiry is deleted, never sent.
  s.g.state.answers.length = 0; s.g.state.answers.push(fcmError(503, 'UNAVAILABLE'));
  await s.call('POST', '/v1/push/events', { ...s.event, eventRef: 'e'.repeat(64) });
  const before = s.g.state.sends.length;
  s.advance(3600001); await s.reconcile();
  assert.equal(s.g.state.sends.length, before); assert.equal((await s.jobs()).length, 0);
});

test('replacing an iPhone with an Android phone, and back, moves delivery and drops the old queue', async t => {
  const s = await service(t);
  await s.call('PUT', '/v1/push/device', s.iphone);
  s.apnsOutcome('retry'); await s.call('POST', '/v1/push/events', s.event);
  assert.equal(s.apnsCalls.length, 1); assert.equal((await s.jobs()).length, 1);
  assert.equal((await s.call('PUT', '/v1/push/device', { ...s.android, revision: 2 })).status, 200);
  assert.equal((await s.jobs()).length, 0, 'the iPhone\'s pending job cannot reach the new phone');
  s.advance(300000); await s.reconcile(); assert.equal(s.apnsCalls.length, 1);
  assert.equal((await s.call('POST', '/v1/push/events', { ...s.event, revision: 2 })).status, 202);
  assert.equal(s.g.state.sends.length, 1); assert.equal(s.apnsCalls.length, 1);
  // Same revision, same Android registration: idempotent. Same revision, anything else: conflict.
  assert.equal((await s.call('PUT', '/v1/push/device', { ...s.android, revision: 2 })).status, 200);
  assert.equal((await s.call('PUT', '/v1/push/device', { ...s.iphone, revision: 2 })).status, 409);
  assert.equal((await s.call('PUT', '/v1/push/device', { ...s.android, revision: 2, token: 'y'.repeat(160) })).status, 409);
  // Reverse transition.
  s.apnsOutcome('sent');
  assert.equal((await s.call('PUT', '/v1/push/device', { ...s.iphone, revision: 3 })).status, 200);
  const row = await s.row(); assert.equal(row.platform, 'apns'); assert.equal(row.environment, 'sandbox');
  await s.call('POST', '/v1/push/events', { ...s.event, eventRef: 'f'.repeat(64), revision: 3 });
  assert.equal(s.apnsCalls.length, 2); assert.equal(s.g.state.sends.length, 1);
  // Revocation clears the platform with the token.
  assert.equal((await s.call('PUT', '/v1/push/device', { revision: 4, generation: 1, deviceHash: null, token: null, route: 'tailnet' })).status, 200);
  const revoked = await s.row(); assert.equal(revoked.token, null); assert.equal(revoked.platform, null);
});

test('schema 3 migrates a live schema-2 database in place; the deployed schema-2 Worker keeps working meanwhile', async t => {
  const schema = readFileSync(join(__dirname, '../service/connect/schema.sql'), 'utf8');
  const [migration] = schema.split('\n').filter(line => line.startsWith('-- migrate 3: ')).map(line => line.slice('-- migrate 3: '.length));
  assert.match(migration, /^ALTER TABLE push_bindings ADD COLUMN platform TEXT/);
  const schema2 = schema.replace(/,\n  platform TEXT CHECK \(platform IS NULL OR platform IN \('apns','fcm'\)\)\n\);/, '\n);');
  assert.notEqual(schema2, schema, 'the schema-2 shape is derived by removing exactly the new column');
  const columns = db => db.prepare('PRAGMA table_info(push_bindings)').all().map(({ name, type, notnull }) => [name, type, notnull]);
  const old = new DatabaseSync(':memory:'), fresh = new DatabaseSync(':memory:'); t.after(() => { old.close(); fresh.close(); });
  old.exec(schema2); fresh.exec(schema);
  // A binding written by the deployed schema-2 Worker, with exactly its statement.
  const schema2Insert = 'INSERT INTO push_bindings(host_id,revision,device_hash,token,environment,topic,route,generation,updated_at) VALUES(?,?,?,?,?,?,?,?,?)';
  old.prepare(schema2Insert).run('a'.repeat(32), 1, 'a'.repeat(64), 'd'.repeat(64), 'sandbox', 'dev.richos.mobile.integration', 'tailnet', 1, 1);
  old.exec(migration);
  assert.deepEqual(columns(old), columns(fresh), 'the migrated table has exactly the fresh schema-3 shape');
  const row = old.prepare('SELECT * FROM push_bindings').get();
  assert.equal(row.platform, null); assert.equal(row.token, 'd'.repeat(64));
  // Between migration and upload the schema-2 Worker still writes; afterwards bad values are refused.
  old.prepare(schema2Insert).run('b'.repeat(32), 1, null, null, null, null, 'tailnet', 1, 1);
  assert.throws(() => old.prepare("UPDATE push_bindings SET platform='gcm'").run(), /CHECK constraint/);
  assert.throws(() => old.exec(migration), /duplicate column/, 'a second run refuses loudly instead of changing anything');
  const { platformOf } = await import('../service/connect/notifications.mjs');
  assert.equal(platformOf(row), 'apns', 'a pre-migration row is APNs to the schema-3 code');
});

test('a schema-2 APNs binding still delivers through APNs after the schema-3 Worker is deployed', async t => {
  const s = await service(t);
  await s.call('PUT', '/v1/push/device', s.iphone);
  // The row as the schema-2 Worker left it: no platform value.
  await s.store.statement('UPDATE push_bindings SET platform=NULL WHERE host_id=?', s.id.id).run();
  assert.equal((await s.call('POST', '/v1/push/events', s.event)).status, 202);
  assert.equal(s.apnsCalls.length, 1); assert.equal(s.g.state.requests.length, 0);
  // Re-sending the unchanged registration from an older Mac is still the same registration.
  assert.equal((await s.call('PUT', '/v1/push/device', s.iphone)).status, 200);
});

test('rolling the Worker back to schema 2 can never send an FCM token to Apple', async () => {
  const { configuredPush } = await import('../service/connect/apns.mjs');
  const env = { APNS_TEAM_ID: 'A123456789', APNS_SANDBOX_KEY_ID: 'B123456789', APNS_SANDBOX_KEY: 'k', APNS_PRODUCTION_KEY_ID: 'C123456789', APNS_PRODUCTION_KEY: 'k', APNS_TOPICS: `dev.richos.mobile.integration,${APP}` };
  // An FCM row has no APNs environment, so the schema-2 APNs gate refuses it even if its topic were allowlisted.
  assert.equal(configuredPush(env, { ...binding, environment: null }), false);
});

test('the managed artifact uploads connect/fcm.mjs, resolves every import and carries FCM identifiers only', async () => {
  const { managedArtifact } = await import('../cli/connect.mjs');
  const profile = { accountId: 'a'.repeat(32), zoneId: 'b'.repeat(32), databaseId: crypto.randomUUID(), domain: 'example.com', capacity: 10,
    fcm: { projectId: PROJECT, apps: [APP] } };
  const artifact = managedArtifact(profile), names = artifact.modules.map(module => module.name);
  assert(names.includes('connect/fcm.mjs'));
  for (const module of artifact.modules) {
    for (const [, specifier] of module.source.matchAll(/^import\s+(?:[^'"]*from\s+)?['"](\.[^'"]+)['"]/gm)) {
      assert(names.includes(new URL(specifier, 'file:///' + module.name).pathname.slice(1)), `${module.name} imports ${specifier}`);
    }
  }
  const bindings = Object.fromEntries(artifact.metadata.bindings.map(row => [row.name, row]));
  assert.deepEqual(bindings.FCM_PROJECT_ID, { name: 'FCM_PROJECT_ID', type: 'plain_text', text: PROJECT });
  assert.deepEqual(bindings.FCM_APPS, { name: 'FCM_APPS', type: 'plain_text', text: APP });
  assert.equal(bindings.FCM_SERVICE_ACCOUNT, undefined, 'the key is a preserved secret, never part of the upload');
  assert.deepEqual(artifact.metadata.keep_bindings, ['secret_text']);
  const without = managedArtifact({ ...profile, fcm: undefined });
  assert(!without.metadata.bindings.some(row => row.name.startsWith('FCM_')), 'no FCM profile, no FCM bindings');
  for (const fcm of [{ projectId: 'X' }, { projectId: PROJECT }, { projectId: PROJECT, apps: [] }, { projectId: PROJECT, apps: ['not-an-id'] },
    { projectId: PROJECT, apps: [APP], serviceAccount: '{}' }, { apps: [APP] }]) {
    assert.throws(() => managedArtifact({ ...profile, fcm }), /FCM/, JSON.stringify(fcm));
  }
});
