#!/usr/bin/env bash
# run-tests.sh — the testvm harness, tested without a virtual machine.
#
#   testvm/test/run-tests.sh            run everything
#   testvm/test/run-tests.sh <pattern>  run the tests whose names match
#
# ===========================================================================
# WHY THESE EXIST, AND WHY THEY DO NOT BOOT A GUEST
# ===========================================================================
# At 07cb236b the harness had no tests at all: the only way to find out whether
# a change to it worked was to clone a 25 GB image, boot it, and read a
# screenshot — five minutes per attempt, and the interesting failures (a key
# leaking into a command line, a refusal that names the wrong action, an exit
# code read off the wrong end of a pipe) are invisible in a screenshot anyway.
#
# Everything here runs against a STUB GUEST and a temporary root, in under a
# second, and asserts the things that would otherwise be found by a person:
#
#   * the auth key never appears in a command line, and never in output;
#   * a missing key refuses exactly ONE step, names ONE action, and does not
#     touch the guest at all;
#   * the name is READ BACK from the daemon, never constructed from the name we
#     asked for;
#   * a certificate is only re-used when it is for the right name and outlives
#     the app's own 720h floor;
#   * `stop.sh`'s sign-out actually signs out.
#
# What they deliberately do NOT cover: whether a real tailnet accepts a real
# key. That needs the CEO's account. `tailnet.sh doctor <vm>` answers it in one
# command against a live guest, which is where that question belongs.
# ===========================================================================
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TESTVM_DIR="$(cd "$HERE/.." && pwd)"
FILTER="${1:-}"

TMP="$(mktemp -d "${TMPDIR:-/tmp}/testvm-tests.XXXXXX")"
# §54: this scratch directory goes however this script ends — pass, fail, or
# an interrupt from a keyboard.
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT INT TERM

PASS=0; FAIL=0; FAILED_NAMES=()

t() {  # t <name> — begin a test; body follows, ended by `t_done`
  CURRENT="$1"
  CURRENT_FAILED=0
}
t_done() {
  case "$CURRENT" in *"$FILTER"*) ;; *) return 0 ;; esac
  if [ "$CURRENT_FAILED" -eq 0 ]; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "$CURRENT"
  else
    FAIL=$((FAIL+1)); FAILED_NAMES+=("$CURRENT"); printf '  FAIL %s\n' "$CURRENT"
  fi
}
ok()   { if [ "$1" -eq 0 ]; then :; else CURRENT_FAILED=1; printf '       expected success: %s\n' "${2:-}"; fi; }
no()   { if [ "$1" -ne 0 ]; then :; else CURRENT_FAILED=1; printf '       expected failure: %s\n' "${2:-}"; fi; }
eq()   { if [ "$1" = "$2" ]; then :; else CURRENT_FAILED=1; printf '       expected [%s] got [%s]  %s\n' "$2" "$1" "${3:-}"; fi; }
has()  { case "$1" in *"$2"*) ;; *) CURRENT_FAILED=1; printf '       expected to contain [%s]:\n%s\n' "$2" "$1" ;; esac; }
hasnt(){ case "$1" in *"$2"*) CURRENT_FAILED=1; printf '       expected NOT to contain [%s]:\n%s\n' "$2" "$1" ;; *) ;; esac; }

# --- the harness under test, rooted somewhere disposable --------------------
export TESTVM_ROOT="$TMP/root"
export TART_HOME="$TMP/root/tart"
mkdir -p "$TESTVM_ROOT"
export TESTVM_AUTHKEY="$TESTVM_ROOT/tailscale.authkey"
export TESTVM_CERTCACHE="$TESTVM_ROOT/certs"
export TESTVM_GUEST_EXEC="$HERE/stub-guest.sh"
export STUB_GUEST_FS="$TMP/guestfs"
mkdir -p "$STUB_GUEST_FS"

. "$TESTVM_DIR/lib.sh"
set +e

# A key that is shaped like a real one and is not one. The literal below is the
# reason this file says `dialect-exempt` to nothing and `not-a-secret` here: it
# is 40 characters of the letter pattern Tailscale uses, generated by hand.
FAKE_KEY="tskey-auth-kTESTkTESTkTEST-notarealkeyatall"

write_key() {  # write_key <mode> <contents...>
  local mode="$1"; shift
  printf '%s' "$*" > "$TESTVM_AUTHKEY"
  chmod "$mode" "$TESTVM_AUTHKEY"
}

# A real certificate, made here, so the cache rules are tested against x509 and
# not against a string. Two names and two lifetimes: the one the cache should
# accept, and the two it must refuse.
make_cert() {  # make_cert <dir> <cn> <days>
  local dir="$1" cn="$2" days="$3"
  mkdir -p "$dir"
  openssl req -x509 -newkey rsa:2048 -nodes -days "$days" \
    -subj "/CN=$cn" -addext "subjectAltName=DNS:$cn" \
    -keyout "$dir/key.pem" -out "$dir/cert.pem" >/dev/null 2>&1
}

echo "testvm tests  (root: $TESTVM_ROOT)"

# ===========================================================================
# tailnet_node_name — the name a VM joins under
# ===========================================================================
t "node name: a bare VM name gets the richos-test- prefix reap.sh looks for"
  eq "$(tailnet_node_name a)" "richos-test-a"
t_done

t "node name: an already-prefixed VM name is left alone, never doubled"
  eq "$(tailnet_node_name richos-test-b)" "richos-test-b"
t_done

t "node name: uppercase is lowercased, because DNS names are"
  eq "$(tailnet_node_name RichOS-Test-C)" "richos-test-c"
t_done

t "node name: an illegal character is REFUSED, not sanitized into a different node"
  tailnet_node_name "a_b" >/dev/null 2>&1; no $? "underscore"
  tailnet_node_name "a.b" >/dev/null 2>&1; no $? "dot"
  tailnet_node_name "a b" >/dev/null 2>&1; no $? "space"
  tailnet_node_name ""    >/dev/null 2>&1; no $? "empty"
t_done

t "node name: over a DNS label's 63 characters is refused"
  long="$(printf 'x%.0s' $(seq 1 70))"
  tailnet_node_name "$long" >/dev/null 2>&1; no $? "70 characters"
t_done

# ===========================================================================
# redact_keys — nothing that has seen a key prints one
# ===========================================================================
t "redaction: a key in a line of output never survives the filter"
  out="$(printf 'backend error: %s is invalid\n' "$FAKE_KEY" | redact_keys)"
  hasnt "$out" "notarealkeyatall"
  has   "$out" "tskey-<redacted>"
t_done

# ===========================================================================
# authkey_problem — the refusal, and what it says
# ===========================================================================
t "auth key: a missing file names the file and does not pretend otherwise"
  rm -f "$TESTVM_AUTHKEY"
  out="$(authkey_problem)"; no $? "missing key must be a problem"
  has "$out" "$TESTVM_AUTHKEY"
t_done

t "auth key: a world-readable key is refused with the chmod that fixes it"
  write_key 644 "$FAKE_KEY"
  out="$(authkey_problem)"; no $?
  has "$out" "chmod 600"
t_done

t "auth key: an empty file is refused"
  write_key 600 ""
  out="$(authkey_problem)"; no $?
  has "$out" "empty"
t_done

t "auth key: a file with more than the key in it is refused"
  printf '%s\nand a note about it\n' "$FAKE_KEY" > "$TESTVM_AUTHKEY"; chmod 600 "$TESTVM_AUTHKEY"
  out="$(authkey_problem)"; no $?
  has "$out" "non-empty lines"
t_done

t "auth key: something that is not a tailscale key is refused BEFORE it is used"
  write_key 600 "hunter2"
  out="$(authkey_problem)"; no $?
  has "$out" "tskey-"
t_done

t "auth key: no refusal ever prints the key itself"
  for bad in "$FAKE_KEY" "$FAKE_KEY extra" ""; do
    printf '%s' "$bad" > "$TESTVM_AUTHKEY"; chmod 644 "$TESTVM_AUTHKEY"
    out="$(authkey_problem 2>&1)"
    hasnt "$out" "notarealkeyatall"
  done
t_done

t "auth key: a well-formed key at mode 600 is no problem at all"
  write_key 600 "$FAKE_KEY"
  out="$(authkey_problem)"; ok $? "a good key must pass"
  eq "$out" ""
t_done

# ===========================================================================
# the certificate cache — validated against x509, not against a filename
# ===========================================================================
t "cert cache: a certificate for the right name, good for longer than 720h, is used"
  make_cert "$(cert_cache_dir good.example.ts.net)" "good.example.ts.net" 90
  cert_cache_usable "good.example.ts.net"; ok $?
t_done

t "cert cache: a certificate for a DIFFERENT name is refused"
  make_cert "$(cert_cache_dir wrong.example.ts.net)" "somebody-else.example.ts.net" 90
  cert_cache_usable "wrong.example.ts.net"; no $?
t_done

t "cert cache: a certificate expiring inside the app's own 720h floor is refused"
  make_cert "$(cert_cache_dir soon.example.ts.net)" "soon.example.ts.net" 10
  cert_cache_usable "soon.example.ts.net"; no $?
t_done

t "cert cache: a missing key file makes the entry unusable, not half-usable"
  make_cert "$(cert_cache_dir half.example.ts.net)" "half.example.ts.net" 90
  rm -f "$(cert_cache_dir half.example.ts.net)/key.pem"
  cert_cache_usable "half.example.ts.net"; no $?
t_done

t "cert cache: a concatenated PEM is split by LABEL, not by order"
  src="$TMP/src"; make_cert "$src" "split.example.ts.net" 90
  # key FIRST, which is the order nothing promises and everything must survive
  bundle="$(cat "$src/key.pem" "$src/cert.pem")"
  cert_cache_store "split.example.ts.net" "$bundle"; ok $?
  cert_cache_usable "split.example.ts.net"; ok $?
  head -1 "$(cert_cache_dir split.example.ts.net)/cert.pem" | grep -q 'BEGIN CERTIFICATE'; ok $?
t_done

t "cert cache: a bundle with no key is not stored at all"
  src="$TMP/src2"; make_cert "$src" "nokey.example.ts.net" 90
  cert_cache_store "nokey.example.ts.net" "$(cat "$src/cert.pem")"; no $?
  [ -e "$(cert_cache_dir nokey.example.ts.net)/cert.pem" ]; no $? "a rejected bundle must leave nothing behind"
t_done

t "cert cache: the stored key is not readable by anyone else"
  src="$TMP/src3"; make_cert "$src" "mode.example.ts.net" 90
  cert_cache_store "mode.example.ts.net" "$(cat "$src/cert.pem" "$src/key.pem")" >/dev/null
  eq "$(stat -f '%Lp' "$(cert_cache_dir mode.example.ts.net)/key.pem")" "600"
t_done

# ===========================================================================
# tailnet.sh join — the refusal path, which is the path without his key
# ===========================================================================
t "join: with no key it refuses ONE step, names the admin console, and exits nonzero"
  rm -f "$TESTVM_AUTHKEY"
  out="$(env STUB_LOG="$TMP/log.norefuse" "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>&1)"; no $?
  has "$out" "NOT JOINED"
  has "$out" "login.tailscale.com/admin/settings/keys"
  has "$out" "Ephemeral: ON"
  has "$out" "Everything else in this VM still works"
t_done

t "join: with no key it does not touch the guest at all"
  rm -f "$TESTVM_AUTHKEY"
  : > "$TMP/log.untouched"
  STUB_LOG="$TMP/log.untouched" "$TESTVM_DIR/tailnet.sh" join richos-test-a >/dev/null 2>&1
  eq "$(wc -l < "$TMP/log.untouched" | tr -d ' ')" "0" "the guest must be left alone"
t_done

t "join: an unusable VM name is refused before the key is even read"
  write_key 600 "$FAKE_KEY"
  : > "$TMP/log.badname"
  out="$(env STUB_LOG="$TMP/log.badname" "$TESTVM_DIR/tailnet.sh" join "bad name" 2>&1)"; no $?
  has "$out" "legal tailnet node name"
  eq "$(wc -l < "$TMP/log.badname" | tr -d ' ')" "0"
t_done

# ===========================================================================
# tailnet.sh join — the path with a key, against the stub guest
# ===========================================================================
t "join: the key reaches the guest as a FILE and never as a command argument"
  write_key 600 "$FAKE_KEY"
  : > "$TMP/log.key"
  src="$TMP/certsrc"; make_cert "$src" "richos-test-a.tail770f6e.ts.net" 90
  cat "$src/cert.pem" "$src/key.pem" > "$TMP/cert.bundle"
  out="$(env STUB_LOG="$TMP/log.key" STUB_CERT_PEM="$TMP/cert.bundle" "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>&1)"
  log="$(cat "$TMP/log.key")"
  hasnt "$log" "notarealkeyatall"          # not in any command line
  has   "$log" "--auth-key 'file:"          # passed by reference
  hasnt "$out" "notarealkeyatall"          # not in any output
t_done

t "join: the staged key held the real bytes, and is deleted from the guest afterwards"
  write_key 600 "$FAKE_KEY"
  : > "$TMP/log.staged"; rm -f "$TMP/staged.copy"
  STUB_LOG="$TMP/log.staged" STUB_CERT_PEM="$TMP/cert.bundle" STUB_KEEP_STAGED="$TMP/staged.copy" \
    "$TESTVM_DIR/tailnet.sh" join richos-test-a >/dev/null 2>&1
  # ARRIVED: the guest really was handed the key, so "the file is gone" below
  # is not equally true of a key that was never written.
  eq "$(cat "$TMP/staged.copy" 2>/dev/null)" "$FAKE_KEY" "the key must reach the guest intact"
  # AND LEFT.
  has "$(cat "$TMP/log.staged")" "rm -f '/Users/$TESTVM_GUEST_USER/.richos-testvm-authkey'"
  [ -e "$STUB_GUEST_FS/Users/$TESTVM_GUEST_USER/.richos-testvm-authkey" ]; no $? "the key must not survive the join"
t_done

t "join: every flag the guest is given is the one that was argued for"
  write_key 600 "$FAKE_KEY"
  : > "$TMP/log.flags"
  STUB_LOG="$TMP/log.flags" STUB_CERT_PEM="$TMP/cert.bundle" \
    "$TESTVM_DIR/tailnet.sh" join richos-test-a >/dev/null 2>&1
  log="$(cat "$TMP/log.flags")"
  has "$log" "--hostname 'richos-test-a'"
  has "$log" "--operator '$TESTVM_GUEST_USER'"     # so the APP can fetch a cert
  has "$log" "--reset"                             # a known state, not an inherited one
  has "$log" "--accept-dns=true"                   # Safari in the guest resolves the name
  has "$log" "--shields-up=false"                  # the phone's connection is inbound
  has "$log" "--ssh=false"
  has "$log" "--timeout 90s"                       # never `up`'s "blocks forever" default
t_done

t "join: it prints the name the DAEMON reports, not the one it asked for"
  write_key 600 "$FAKE_KEY"
  out="$(env STUB_LOG=/dev/null STUB_CERT_PEM="$TMP/cert.bundle" STUB_DNSNAME="richos-test-a-1.tail770f6e.ts.net" "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>/dev/null)"
  eq "$(printf '%s\n' "$out" | tailnet_name_from_join_output)" "richos-test-a-1.tail770f6e.ts.net"
t_done

t "join: a collided name is CALLED OUT, because every URL built from it would be wrong"
  write_key 600 "$FAKE_KEY"
  err="$(env STUB_LOG=/dev/null STUB_CERT_PEM="$TMP/cert.bundle" STUB_DNSNAME="richos-test-a-1.tail770f6e.ts.net" "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>&1 >/dev/null)"
  has "$err" "asked for 'richos-test-a'"
t_done

t "join: a certificate that came back is cached under the name the daemon gave"
  rm -rf "$TESTVM_CERTCACHE/richos-test-a.tail770f6e.ts.net"
  write_key 600 "$FAKE_KEY"
  STUB_LOG=/dev/null STUB_CERT_PEM="$TMP/cert.bundle" \
    "$TESTVM_DIR/tailnet.sh" join richos-test-a >/dev/null 2>&1
  cert_cache_usable "richos-test-a.tail770f6e.ts.net"; ok $? "the cache must hold a usable cert"
t_done

t "join: the second run offers the cached certificate back to the guest"
  write_key 600 "$FAKE_KEY"
  : > "$TMP/log.reuse"
  STUB_LOG="$TMP/log.reuse" STUB_CERT_PEM="$TMP/cert.bundle" \
    "$TESTVM_DIR/tailnet.sh" join richos-test-a >/dev/null 2>&1
  has "$(cat "$TMP/log.reuse")" "certs/richos-test-a.tail770f6e.ts.net.crt"
t_done

t "join: a key the tailnet refuses is reported as a key problem, not as a mystery"
  write_key 600 "$FAKE_KEY"
  out="$(env STUB_LOG=/dev/null STUB_MODE=invalid-key "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>&1)"; no $?
  has "$out" "expired, revoked, or single-use"
  has "$out" "Generate auth key"
t_done

t "join: a tailnet that will not certify the node says so, and says whose switch it is"
  write_key 600 "$FAKE_KEY"
  out="$(env STUB_LOG=/dev/null STUB_MODE=certs-off "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>&1)"; no $?
  has "$out" "will not issue it a certificate"
  has "$out" "admin/dns"
  has "$out" "certificates=off"
t_done

t "join: a daemon that never reaches Running is a refusal, never a silent pass"
  write_key 600 "$FAKE_KEY"
  # Two polls, no sleep between them: the refusal is what is under test, not
  # the patience in front of it.
  out="$(env STUB_LOG=/dev/null STUB_MODE=never-running TESTVM_JOIN_POLLS=2 TESTVM_JOIN_POLL_SECONDS=0 "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>&1)"; no $?
  has "$out" "never reached Running"
t_done

t "join: no certificate means a loud warning — the app would refuse to pair"
  write_key 600 "$FAKE_KEY"
  out="$(env STUB_LOG=/dev/null STUB_MODE=no-cert "$TESTVM_DIR/tailnet.sh" join richos-test-a 2>&1)"
  has "$out" "would not hand over a certificate"
t_done

# ===========================================================================
# logout — §54 at the tailnet
# ===========================================================================
t "logout: it signs the guest out and then CHECKS that it is signed out"
  marker="$TMP/logged-out"; rm -f "$marker"
  : > "$TMP/log.logout"
  out="$(env STUB_LOG="$TMP/log.logout" STUB_LOGOUT_MARKER="$marker" "$TESTVM_DIR/tailnet.sh" logout richos-test-a 2>&1)"; ok $?
  has "$(cat "$TMP/log.logout")" "tailscale logout"
  has "$out" "signed out"
t_done

t "logout: a guest that stays signed in is reported as a failure, not as done"
  : > "$TMP/log.stuck"
  out="$(env STUB_LOG="$TMP/log.stuck" "$TESTVM_DIR/tailnet.sh" logout richos-test-a 2>&1)"; no $?
  has "$out" "STILL signed in"
t_done

t "logout: a guest that was never signed in is a no-op, not an error"
  STUB_LOG=/dev/null STUB_MODE=signed-out \
    "$TESTVM_DIR/tailnet.sh" logout richos-test-a >/dev/null 2>&1; ok $?
t_done

# ===========================================================================
# nodes — the host's view, which is the only one that outlives a dead guest
# ===========================================================================
t "nodes: richos-test-* peers are listed, and nobody else's machines are"
  cat > "$TMP/fake-ts" <<'STUB'
#!/usr/bin/env bash
cat <<'JSON'
{"BackendState":"Running","Self":{"DNSName":"mm1.tail770f6e.ts.net."},
 "Peer":{"k1":{"HostName":"richos-test-a","DNSName":"richos-test-a.tail770f6e.ts.net.","Online":true},
         "k2":{"HostName":"richos-test-b","DNSName":"richos-test-b.tail770f6e.ts.net.","Online":false},
         "k3":{"HostName":"alexs-iphone","DNSName":"alexs-iphone.tail770f6e.ts.net.","Online":true}}}
JSON
STUB
  chmod +x "$TMP/fake-ts"
  out="$(TESTVM_HOST_TS="$TMP/fake-ts" "$TESTVM_DIR/tailnet.sh" nodes 2>&1)"
  has   "$out" "richos-test-a"
  has   "$out" "richos-test-b"
  has   "$out" "offline"
  hasnt "$out" "alexs-iphone"
t_done

t "nodes: a Mac with no tailscale on it answers calmly instead of failing"
  out="$(TESTVM_HOST_TS="$TMP/nothing-here" "$TESTVM_DIR/tailnet.sh" nodes 2>&1)"; ok $?
  has "$out" "no tailscale command line"
t_done

# ===========================================================================
# the contract between tailnet.sh's output and run.sh's summary
# ===========================================================================
t "summary: run.sh reads the name out of join's output, in both of its shapes"
  eq "$(printf 'tailnet=richos-test-a.tail770f6e.ts.net\n' | tailnet_name_from_join_output)" "richos-test-a.tail770f6e.ts.net"
  eq "$(printf 'tailnet=richos-test-b.tail770f6e.ts.net certificates=off\n' | tailnet_name_from_join_output)" "richos-test-b.tail770f6e.ts.net"
  eq "$(printf 'no tailnet here\n' | tailnet_name_from_join_output)" ""
t_done

t "summary: run.sh still accepts --no-tailnet and still requires its real arguments"
  out="$("$TESTVM_DIR/run.sh" --no-tailnet 2>&1)"; no $?
  has "$out" "--bundle is required"
t_done

# ===========================================================================
echo
if [ "$FAIL" -eq 0 ]; then
  echo "$PASS passed, 0 failed."
  exit 0
fi
echo "$PASS passed, $FAIL FAILED:"
for n in ${FAILED_NAMES[@]+"${FAILED_NAMES[@]}"}; do echo "  - $n"; done
exit 1
