#!/usr/bin/env bash
# run-tests: inputs richos/app/scripts/lint richos/app/scripts/lint.sh richos/app/scripts/lint.test.sh richos/app/scripts/lint-regressions.test.sh richos/app/scripts/nightly-local.py richos/app/.shellcheckrc richos/app/scripts/lib/cargo-cache-env.sh richos/app/scripts/lib/cargo_identity.py richos/app/scripts/bin richos/app/scripts/bin/cargo richos/engine/scripts richos/engine/orchestration.config richos/engine/scripts/hooks/guard-dialect.sh richos/engine/scripts/lib/resolve-roots.sh richos/engine/scripts/lib/resolve-main-checkout.sh richos/engine/scripts/lib/seat-jurisdiction.sh richos/engine/scripts/lib/unevaluated-notice.sh richos/engine/scripts/lib/vendored-material.sh richos/engine/scripts/lib/declaration-path.sh richos/engine/scripts/lib/dialect-en-US.dict
# run-tests: covers richos/app/scripts/lint/driver.py richos/app/scripts/lint/common.py richos/app/scripts/lint/rust.py richos/app/scripts/lint/ratchet.py richos/app/scripts/lint/dialect.py richos/app/scripts/lint/process_rules.py richos/app/scripts/lint/shell_source.py richos/app/scripts/lint/timeout_rules.py richos/app/scripts/lint/suite_rules.py richos/app/scripts/lint/advisory_rules.py richos/app/scripts/lint/test_advisory.py richos/app/scripts/lint/test_dialect.py richos/app/scripts/lint/test_execution.py richos/app/scripts/lint/test_inputs.py richos/app/scripts/lint/test_process.py richos/app/scripts/lint/test_ratchet.py richos/app/scripts/lint/test_suite.py richos/app/scripts/lint/test_timeout.py richos/app/scripts/lint/test_wiring.py richos/app/scripts/lint/load_rules.py richos/app/scripts/lint/test_load.py richos/app/scripts/lint/test_changed.py richos/app/scripts/lint.sh
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PYTHONDONTWRITEBYTECODE=1
# These fixtures prove the lint machinery; lint.test.sh scans the current product.
python3 -m unittest discover -s "$DIR/lint" -p 'test_*.py'
echo '  PASS  lint regression fixtures'
