#!/usr/bin/env bash
# Runs real core tests and separate CLI processes. Packaging assertions exercise
# simulator.mjs without requiring Xcode; they do not claim native behavior.
# run-tests: inputs richos/web/web-app/styles.css richos/mobile/release-config.json richos/mobile/service richos/app/scripts/mobile-headless.test.sh richos/mobile/package.json richos/mobile/core richos/mobile/dev richos/mobile/cli richos/mobile/ui richos/mobile/platform richos/mobile/test richos/web/web-app/lib richos/web/web-app/test/stub-mac.js richos/tools/phone-probe/lib
# run-tests: covers richos/mobile/service/policy-worker.mjs richos/mobile/service/policy-store.mjs richos/mobile/service/policy-hosted.mjs richos/mobile/service/policy-schema.sql richos/mobile/test/policy-worker.test.js richos/mobile/test/policy-worker-runtime.test.js richos/mobile/test/policy-targets.test.js richos/mobile/dev/policy-worker-local.mjs richos/mobile/test/lab-lifetime.test.js richos/web/web-app/lib/voice.js richos/mobile/test/voice-gesture.test.js richos/mobile/service/connect/apns.mjs richos/mobile/service/connect/fcm.mjs richos/mobile/test/connect-fcm.test.js richos/mobile/test/connect-fcm-runtime.test.js richos/mobile/service/connect/notifications.mjs richos/mobile/test/connect-fixture.cjs richos/mobile/test/notifications.test.js richos/mobile/test/client-notifications.test.js richos/mobile/test/client-voice.test.js richos/web/web-app/lib/connection.js richos/mobile/test/connection.test.js richos/mobile/dev/connect-lab.mjs richos/mobile/service/connect-worker.mjs richos/mobile/service/connect/auth.mjs richos/mobile/service/connect/store.mjs richos/mobile/service/connect/provider.mjs richos/mobile/service/connect/lifecycle.mjs richos/mobile/service/connect/schema.sql richos/mobile/test/connect-service.test.js richos/mobile/service/connect-bootstrap.mjs richos/mobile/cli/connect.mjs richos/mobile/test/connect-bootstrap.test.js richos/mobile/dev/policy-lab.mjs richos/mobile/core/links.js richos/mobile/cli/release.mjs richos/mobile/release-config.json richos/mobile/core/updates.js richos/mobile/service/policy.mjs richos/mobile/test/updates.test.js richos/mobile/test/policy-service.test.js richos/mobile/test/client-part2.test.js richos/mobile/dev/update-fixture.js richos/mobile/cli/device.mjs richos/mobile/cli/device-runner.mjs richos/mobile/dev/client-runtime.js richos/mobile/dev/lab.mjs richos/mobile/test/device-runner.test.js richos/mobile/test/lab.test.js richos/mobile/core/client.js richos/mobile/platform/native.js richos/mobile/test/client.test.js richos/mobile/package.json richos/mobile/core/app.js richos/mobile/dev/runtime.js richos/mobile/cli/mobile.mjs richos/mobile/cli/simulator.mjs richos/mobile/ui/entry.js richos/mobile/test/core.test.js richos/mobile/test/cli.test.js richos/mobile/test/run-suite.cjs richos/mobile/test/storage.cjs
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$DIR/../../.." && pwd)"
for tool in node npm; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "  NOT RUN  mobile-headless: $tool is unavailable"
    exit 2
  fi
done
node "$ROOT/richos/mobile/test/run-suite.cjs" headless
echo '  PASS  mobile headless core, CLI persistence/errors and resource packaging'
