#!/usr/bin/env bash
#
# signing-setup.test.sh — make-signing-csr.sh and install-signing-cert.sh.
#
# ONE SUITE FOR TWO SCRIPTS, deliberately. The certificate installer's fixtures
# ARE the CSR script's outputs: a key it generated, and certificates signed by that
# key. Splitting them would mean one suite re-deriving the other's artefacts with
# openssl by hand, which is a second implementation of the thing under test.
#
# WHAT IS REAL HERE AND WHAT IS NOT. The keys, CSRs and certificates below are
# real: generated by the real openssl, and the modulus and certificate-type checks
# run against them. What is NOT real is Apple — every certificate here is
# self-signed. A real Developer ID Application certificate HAS existed on this
# machine since 2026-09-01, and this suite still does not use it: an operator's
# signing identity is not a test fixture, and a suite that wrote to the login
# keychain would be a worse defect than any it could catch. So case F6 reaches the
# keychain import behind a `security` SHIM, and case Z proves the operator's real
# keychain was untouched.
#
# AND THE SHIM IS WHY THIS SUITE PASSED WHILE THE INSTALLER WAS BROKEN. On the
# night the real certificate arrived, every case below was green and the script
# failed against it at the first attempt: a shim accepts a PKCS#12 that macOS
# refuses. The G cases exist for exactly that gap — they test what a shim cannot
# paper over.
#
# Cases:
#   E1  a key directory inside a git worktree is REFUSED
#   E2  the generated key is RSA 2048, the CSR is SHA-256, modes are 600/700
#   E3  a second run does not overwrite an existing key
#   E4  ...and --force does, which is what makes E3 mean something
#   E5  a country code that is not two upper-case letters is refused
#   E6  --show on an empty directory says ABSENT rather than inventing a state
#   E7  --show reports the subject of a CSR that exists
#   F1  no argument -> refuse
#   F2  a .cer that does not exist -> refuse
#   F3  the private key missing -> refuse, and say why a .cer alone is useless
#   F4  a certificate issued against a DIFFERENT key -> refuse on the modulus
#   F5  a certificate that is not "Developer ID Application" -> refuse, by name
#   F6  [shim] the matching, correctly-typed certificate reaches "installed and usable"
#   F7  [shim] ...and the Team ID is read out of the identity string
#   F8  ...and the passphrase-less PKCS#12 does not survive the import
#   F9  [shim] an import that reports success and yields NO identity is a FAILURE
#   G1  the entitlements file the signing path passes codesign is one codesign ACCEPTS
#   G2  no `security import` anywhere omits -P, so none of them can raise a dialog
#   G3  an encrypted private key is refused BEFORE any keychain call
#   G4  the openssl is the pinned one; the one on PATH is never called
#   G5  an openssl that exits 0 and leaves a 0-byte file is caught at that step
#   G6  a 0-byte .cer is refused at the conversion, not carried forward
#   G7  an empty --keychain is a FAILURE even when the login keychain holds one
#   G8  [shim] --check LISTS the identity under its own heading
#   G9  [shim] --check exits NON-ZERO when this machine cannot sign
#   G10 no PKCS#12 is built at all, so no passphrase has to travel anywhere
#   Z   the operator's real keychain inventory is unchanged by this suite
set -uo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CSR="$SRC_DIR/make-signing-csr.sh"
INSTALL="$SRC_DIR/install-signing-cert.sh"

TMP="$(mktemp -d -t signing-setup-test.XXXXXX)"
trap 'rm -rf "$TMP"' EXIT
REAL_IDS_BEFORE="$(security find-identity -v -p codesigning 2>/dev/null || true)"

PASS=0; FAIL=0
ok()  { printf '  PASS  %s\n' "$1"; PASS=$((PASS + 1)); }
bad() { printf '  FAIL  %s\n         %s\n' "$1" "${2:-}"; FAIL=$((FAIL + 1)); }
run() { OUT="$("$@" 2>&1)"; CODE=$?; return 0; }
expect() {
  local name="$1" want="$2" needle="$3"
  if [ "$CODE" != "$want" ]; then
    bad "$name" "exit $CODE, wanted $want. Output: $(printf '%s' "$OUT" | tr '\n' ' ' | cut -c1-200)"
  elif ! printf '%s' "$OUT" | grep -Fq -- "$needle"; then
    bad "$name" "exit $want as wanted, but the output never said '$needle'"
  else ok "$name"; fi
}

SHIM="$TMP/shim"; mkdir -p "$SHIM"
cat > "$SHIM/security" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  find-identity)
    echo '  1) DEADBEEF0001 "Developer ID Application: Test Person (TEAM00001)"'
    echo '     1 valid identities found' ;;
  find-certificate) exit 0 ;;
  import)           echo "1 key imported."; echo "1 certificate imported." ;;
  *) exit 1 ;;
esac
exit 0
EOF
chmod +x "$SHIM/security"

echo ""
echo "=== E. make-signing-csr.sh ==="
REPO="$TMP/repo"; mkdir -p "$REPO"; git -C "$REPO" init -q 2>/dev/null
run bash "$CSR" --dir "$REPO/keys" --name "Test Person" --email t@example.com --country GB
expect "E1 a key directory inside a git worktree is refused" 2 "is inside a git worktree"

D="$TMP/keys"
run bash "$CSR" --dir "$D" --name "Test Person" --email t@example.com --country GB
if [ "$CODE" != 0 ]; then
  bad "E2 generation" "exit $CODE: $OUT"
else
  bits="$(openssl rsa -in "$D/developer-id.key" -noout -text 2>/dev/null | sed -n 's/^.*Private-Key: (\([0-9]*\) bit.*/\1/p' | head -1)"
  alg="$(openssl req -in "$D/developer-id.certSigningRequest" -noout -text | sed -n 's/^ *Signature Algorithm: *//p' | head -1)"
  kmode="$(stat -f '%Lp' "$D/developer-id.key")"; dmode="$(stat -f '%Lp' "$D")"
  if [ "$bits" = 2048 ] && [ "$alg" = "sha256WithRSAEncryption" ] && [ "$kmode" = 600 ] && [ "$dmode" = 700 ]; then
    ok "E2 RSA $bits, $alg, key mode $kmode in a $dmode directory"
  else
    bad "E2 the generated material is not what Apple's Certificate Assistant emits" \
        "bits=$bits alg=$alg key=$kmode dir=$dmode"
  fi
fi

KEY_BEFORE="$(shasum -a 256 "$D/developer-id.key" | cut -d' ' -f1)"
run bash "$CSR" --dir "$D" --name "Test Person" --email t@example.com --country GB
KEY_AFTER="$(shasum -a 256 "$D/developer-id.key" | cut -d' ' -f1)"
if [ "$CODE" = 2 ] && [ "$KEY_BEFORE" = "$KEY_AFTER" ]; then
  ok "E3 a second run refuses and leaves the existing key byte-identical"
else
  bad "E3 an existing key was not protected" "exit $CODE, key changed: $([ "$KEY_BEFORE" != "$KEY_AFTER" ] && echo yes || echo no)"
fi

run bash "$CSR" --dir "$D" --name "Test Person" --email t@example.com --country GB --force
if [ "$CODE" = 0 ] && [ "$(shasum -a 256 "$D/developer-id.key" | cut -d' ' -f1)" != "$KEY_BEFORE" ]; then
  ok "E4 --force does overwrite, so E3's refusal is a decision and not an inability"
else
  bad "E4 --force did not overwrite" "exit $CODE"
fi

run bash "$CSR" --dir "$TMP/k2" --name "Test Person" --email t@example.com --country gb
expect "E5 a country code that is not two upper-case letters is refused" 2 "two-letter country code"

run bash "$CSR" --dir "$TMP/never" --show
expect "E6 --show on an empty directory says so rather than inventing a state" 0 "does not exist"
run bash "$CSR" --dir "$D" --show
expect "E7 --show reports the subject of the CSR that exists" 0 "CN=Test Person"

echo ""
echo "=== F. install-signing-cert.sh ==="
run bash "$INSTALL"
expect "F1 no argument -> refuse" 2 "give me the .cer Apple issued"
run bash "$INSTALL" --dir "$D" "$TMP/nope.cer"
expect "F2 a .cer that does not exist -> refuse" 2 "no such file"

mkdir -p "$TMP/keyless"
run bash "$INSTALL" --dir "$TMP/keyless" "$D/developer-id.certSigningRequest"
expect "F3 no private key -> refuse, and say why a .cer alone is useless" 2 "cannot sign anything"

# A certificate from a DIFFERENT key, self-signed, DER — the shape Apple sends.
openssl req -x509 -newkey rsa:2048 -nodes -sha256 -days 2 \
  -keyout "$TMP/other.key" -out "$TMP/other.pem" \
  -subj "/CN=Developer ID Application: Test Person (TEAM00001)" >/dev/null 2>&1
openssl x509 -in "$TMP/other.pem" -outform DER -out "$TMP/other.cer" 2>/dev/null
run bash "$INSTALL" --dir "$D" "$TMP/other.cer"
expect "F4 a certificate issued against a different key -> refuse on the modulus" 2 "public moduli differ"

# The RIGHT key, the WRONG type.
openssl req -new -key "$D/developer-id.key" -sha256 -out "$TMP/wrong.csr" \
  -subj "/CN=Developer ID Installer: Test Person (TEAM00001)" >/dev/null 2>&1
openssl x509 -req -in "$TMP/wrong.csr" -signkey "$D/developer-id.key" -days 2 -sha256 \
  -outform DER -out "$TMP/wrong.cer" >/dev/null 2>&1
run bash "$INSTALL" --dir "$D" "$TMP/wrong.cer"
expect "F5 a Developer ID INSTALLER certificate is refused, by name" 2 "signs .pkg installers only"

# The RIGHT key and the RIGHT type.
openssl req -new -key "$D/developer-id.key" -sha256 -out "$TMP/right.csr" \
  -subj "/CN=Developer ID Application: Test Person (TEAM00001)" >/dev/null 2>&1
openssl x509 -req -in "$TMP/right.csr" -signkey "$D/developer-id.key" -days 2 -sha256 \
  -outform DER -out "$TMP/right.cer" >/dev/null 2>&1
run env PATH="$SHIM:$PATH" bash "$INSTALL" --dir "$D" "$TMP/right.cer"
expect "F6 [shim] the matching, correctly-typed certificate reaches 'installed and usable'" 0 "is installed and usable"
if printf '%s' "$OUT" | grep -Fq "Team ID: TEAM00001"; then
  ok "F7 [shim] ...and the Team ID is read out of the identity string"
else
  bad "F7 the Team ID was not extracted" "$(printf '%s' "$OUT" | tr '\n' ' ' | cut -c1-200)"
fi
if [ -f "$D/developer-id.p12" ]; then
  bad "F8 the unencrypted PKCS#12 was left on disk" "$D/developer-id.p12 still exists"
else
  ok "F8 the passphrase-less PKCS#12 was removed after the import"
fi

# F9 — THE FAILURE THIS SCRIPT WAS WRITTEN FOR. `security import` reporting success
# and no identity resulting is the state that reads like the certificate failed and
# is actually a key/keychain mismatch. Without this case the branch that catches it
# is unreachable in the suite, which was proven: mutation N15 disarmed it and
# nothing went red.
SHIM0="$TMP/shim0"; mkdir -p "$SHIM0"
cat > "$SHIM0/security" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  find-identity)    echo '     0 valid identities found' ;;
  find-certificate) exit 0 ;;
  import)           echo "1 key imported." ;;
  *) exit 1 ;;
esac
exit 0
EOF
chmod +x "$SHIM0/security"
run env PATH="$SHIM0:$PATH" bash "$INSTALL" --dir "$D" "$TMP/right.cer"
expect "F9 [shim] an import that reports success but yields NO identity is a FAILURE" 1 "the import reported success and NO Developer ID Application identity exists"


# ===========================================================================
# G. THE CASES THAT WERE MISSING WHILE THE DEFECTS WERE LIVE.
#
# This suite passed, in full, on the night install-signing-cert.sh failed
# against the first real Developer ID certificate this project has ever had. It
# could not have done otherwise: every case above reaches the keychain through a
# `security` SHIM, and a shim accepts a PKCS#12 that macOS refuses. The shim is
# still right — installing a self-signed certificate calling itself "Developer ID
# Application" into somebody's login keychain would be worse than the bug — but a
# shim that says yes to everything tests nothing about the material.
#
# So these cases test the things a shim CANNOT paper over: which binaries the
# script chooses, what it writes, what it refuses, what it exits, and whether any
# call it makes could stop and wait for a human.
#
# EVERY ONE WAS RUN RED BEFORE IT WAS RUN GREEN, by reverting the fix it covers.
# A negative test never seen to fail is not evidence.
# ===========================================================================
echo ""
echo "=== G. the defects of 2026-09-01 ==="

# --- G1: the entitlements file codesign is handed must be one codesign accepts.
# The Developer ID signing path failed here first, and not in a signing script:
# `--sign` written out literally inside an XML comment is a double hyphen, which
# XML forbids, and codesign answered "AMFIUnserializeXML: syntax error near line 8".
# `plutil -lint` reports the broken file OK, so the obvious check is not evidence.
# Signed ad-hoc (`-s -`) against a throwaway copy of /bin/echo: no keychain, no
# identity, nothing that can prompt — but the same parser that refused the file.
ENTS="$SRC_DIR/../src-tauri/Entitlements.plist"
if [ ! -f "$ENTS" ]; then
  bad "G1 the entitlements file is missing" "$ENTS"
else
  cp /bin/echo "$TMP/ents-probe"
  run codesign --force --sign - --entitlements "$ENTS" "$TMP/ents-probe"
  if [ "$CODE" = 0 ]; then
    ok "G1 codesign accepts src-tauri/Entitlements.plist (plutil -lint would accept a broken one)"
  else
    bad "G1 codesign REFUSES the entitlements file the developer-id path passes it" \
        "$(printf '%s' "$OUT" | tr '\n' ' ' | cut -c1-160)"
  fi
  if python3 -c 'import sys,xml.dom.minidom; xml.dom.minidom.parse(sys.argv[1])' "$ENTS" 2>/dev/null; then
    ok "G1b ...and it is well-formed XML by a strict parser, which is the underlying property"
  else
    bad "G1b the entitlements file is not well-formed XML" "a double hyphen inside the comment is the usual cause"
  fi
fi

# --- G2: NOTHING THIS SCRIPT RUNS MAY BE ABLE TO STOP AND WAIT FOR A HUMAN.
# `security import` WITHOUT -P is not "empty passphrase": it escalates to
# SecurityAgent, puts a dialog on the operator's screen and blocks forever. In CI
# that is an unattended hang with no output. This shim fails the case if any
# import it sees omits -P.
SHIMP="$TMP/shimp"; mkdir -p "$SHIMP"
cat > "$SHIMP/security" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  find-identity)
    echo '  1) DEADBEEF0001 "Developer ID Application: Test Person (TEAM00001)"'
    echo '     1 valid identities found' ;;
  find-certificate) exit 0 ;;
  import)
    seen=0
    for a in "$@"; do [ "$a" = "-P" ] && seen=1; done
    [ "$seen" = 1 ] || { echo "WOULD-PROMPT: security import with no -P"; touch "$SHIM_PROMPT_MARKER"; }
    echo "1 item imported." ;;
  *) exit 1 ;;
esac
exit 0
EOF
chmod +x "$SHIMP/security"
export SHIM_PROMPT_MARKER="$TMP/would-prompt"
rm -f "$SHIM_PROMPT_MARKER"
run env PATH="$SHIMP:$PATH" SHIM_PROMPT_MARKER="$SHIM_PROMPT_MARKER" bash "$INSTALL" --dir "$D" "$TMP/right.cer"
if [ -f "$SHIM_PROMPT_MARKER" ]; then
  bad "G2 an import ran without -P, so this script can hang on a GUI dialog" \
      "$(printf '%s' "$OUT" | tr '\n' ' ' | cut -c1-200)"
else
  ok "G2 every 'security import' passes -P explicitly, so none of them can prompt"
fi

# --- G3: an ENCRYPTED private key is refused BEFORE any keychain call. Handing one
# to `security import` is the other way to raise a passphrase dialog, and
# `openssl rsa` without -passin blocks on a terminal prompt of its own. The shim
# here records ANY use of `security` at all, so the case fails if the refusal
# happens after the keychain was already reached.
SHIMT="$TMP/shimt"; mkdir -p "$SHIMT"
cat > "$SHIMT/security" <<'EOF'
#!/usr/bin/env bash
touch "$SHIM_TOUCH_MARKER"
exit 1
EOF
chmod +x "$SHIMT/security"
ENCDIR="$TMP/enc"; mkdir -p "$ENCDIR"; chmod 700 "$ENCDIR"
/usr/bin/openssl genrsa -aes256 -passout pass:hunter2 -out "$ENCDIR/developer-id.key" 2048 2>/dev/null
export SHIM_TOUCH_MARKER="$TMP/security-was-called"
rm -f "$SHIM_TOUCH_MARKER"
run env PATH="$SHIMT:$PATH" SHIM_TOUCH_MARKER="$SHIM_TOUCH_MARKER" bash "$INSTALL" --dir "$ENCDIR" "$TMP/right.cer"
if [ "$CODE" = 2 ] && printf '%s' "$OUT" | grep -Fq "cannot be read without a passphrase" && [ ! -f "$SHIM_TOUCH_MARKER" ]; then
  ok "G3 an encrypted private key is refused, non-interactively, before any keychain call"
else
  bad "G3 an encrypted key was not refused cleanly ahead of the keychain" \
      "exit $CODE, security called: $([ -f "$SHIM_TOUCH_MARKER" ] && echo yes || echo no)"
fi

# --- G4: the openssl is the PINNED one, not whichever PATH offers. On this machine
# PATH gives Homebrew's OpenSSL 3.6.1 and the OS gives LibreSSL 3.3.6; they disagree
# about DER, about PKCS#12 encryption and about -legacy, and the old script took
# whichever came first. This shim is a poisoned `openssl` early on PATH: if the
# script ever calls it, the marker appears.
SHIMO="$TMP/shimo"; mkdir -p "$SHIMO"
cat > "$SHIMO/openssl" <<'EOF'
#!/usr/bin/env bash
touch "$SHIM_OPENSSL_MARKER"
exit 1
EOF
chmod +x "$SHIMO/openssl"
cp "$SHIMP/security" "$SHIMO/security"
export SHIM_OPENSSL_MARKER="$TMP/path-openssl-was-used"
rm -f "$SHIM_OPENSSL_MARKER" "$SHIM_PROMPT_MARKER"
run env PATH="$SHIMO:$PATH" SHIM_OPENSSL_MARKER="$SHIM_OPENSSL_MARKER" SHIM_PROMPT_MARKER="$SHIM_PROMPT_MARKER" \
      bash "$INSTALL" --dir "$D" "$TMP/right.cer"
if [ ! -f "$SHIM_OPENSSL_MARKER" ] && [ "$CODE" = 0 ]; then
  ok "G4 the openssl on PATH is never used; the pinned one is, and the run still succeeds"
else
  bad "G4 the script used whichever openssl PATH offered" \
      "exit $CODE, PATH openssl called: $([ -f "$SHIM_OPENSSL_MARKER" ] && echo yes || echo no)"
fi

# --- G5: a 0-BYTE ARTIFACT IS CAUGHT WHERE IT IS PRODUCED. LibreSSL fed a DER
# certificate where PEM is expected prints "unable to load certificates", exits 1,
# AND LEAVES A 0-BYTE OUTPUT FILE; the old script's 0-byte PKCS#12 then failed
# three steps later with a misleading error about a wrong parameter. This stub
# openssl reproduces the shape — an empty output file — and the script must refuse
# on the spot and say so.
STUB="$TMP/stubssl"; mkdir -p "$STUB"
cat > "$STUB/openssl" <<'EOF'
#!/usr/bin/env bash
if [ "${1:-}" = "version" ]; then echo "StubSSL 0.0 (writes empty files)"; exit 0; fi
if [ "${1:-}" = "x509" ]; then
  out=""; prev=""
  for a in "$@"; do [ "$prev" = "-out" ] && out="$a"; prev="$a"; done
  [ -n "$out" ] && : > "$out"
  exit 0
fi
exit 1
EOF
chmod +x "$STUB/openssl"
run env RICHOS_OPENSSL="$STUB/openssl" bash "$INSTALL" --dir "$D" "$TMP/right.cer"
expect "G5 an openssl that exits 0 and leaves a 0-byte file is caught at that step" 2 "empty or unusable"

# --- G6: a 0-byte .cer is refused as a certificate, not carried forward.
: > "$TMP/empty.cer"
run bash "$INSTALL" --dir "$D" "$TMP/empty.cer"
expect "G6 a 0-byte .cer is refused as unreadable, at the conversion" 2 "is not a certificate"

# --- G7: THE VERIFICATION MUST READ THE KEYCHAIN THIS RUN WROTE TO. The old script
# asked `security find-identity` with no keychain argument even when --keychain
# named one, so a failed import into keychain X still "found" the identity already
# sitting in login and reported success. This shim answers honestly: the named
# keychain is empty, the default search list is not.
SHIMK="$TMP/shimk"; mkdir -p "$SHIMK"
cat > "$SHIMK/security" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  find-identity)
    # find-identity -v -p codesigning [<keychain>]
    if [ "$#" -ge 5 ]; then echo '     0 valid identities found'
    else
      echo '  1) DEADBEEF0001 "Developer ID Application: Test Person (TEAM00001)"'
      echo '     1 valid identities found'
    fi ;;
  find-certificate) exit 0 ;;
  import)           echo "1 item imported." ;;
  *) exit 1 ;;
esac
exit 0
EOF
chmod +x "$SHIMK/security"
run env PATH="$SHIMK:$PATH" bash "$INSTALL" --dir "$D" --keychain "$TMP/somewhere.keychain-db" "$TMP/right.cer"
expect "G7 an empty --keychain is a FAILURE even when login holds an identity" 1 "NO Developer ID Application identity exists"

# --- G8: --check PRINTS the identities. It used to print its own heading and then
# nothing, because the function that printed them was called with its output sent
# to /dev/null to suppress a count it also returned. The one question the script
# exists to answer was the one its status output did not show.
run env PATH="$SHIMP:$PATH" SHIM_PROMPT_MARKER="$SHIM_PROMPT_MARKER" bash "$INSTALL" --check --dir "$D"
# The needle is the identity's SHA-1, not its name: the name also appears further
# down in the "Developer ID Application identities:" summary, so matching on it
# passed even with the listing suppressed. Measured — the first version of this
# case stayed green under the exact mutation it was written to catch.
expect "G8 [shim] --check lists the identity line itself under its own heading" 0 "DEADBEEF0001"

# --- G9: A FAILURE THAT EXITS 0 IS HOW A BROKEN INSTALL GETS REPORTED AS DONE.
# --check exited 0 on a machine with no identity at all, having said so on stdout.
run env PATH="$SHIM0:$PATH" bash "$INSTALL" --check --dir "$D"
expect "G9 [shim] --check exits NON-ZERO when this machine cannot sign" 1 "cannot sign for distribution"

# --- G10: no PKCS#12 is built at all any more, so there is no unencrypted copy of
# the private key to leave behind and no passphrase to put on a command line. F8
# above proves the file is absent; this proves the script does not even try, which
# is the difference between cleaning up after a hazard and not creating one.
if grep -n 'pkcs12 -export' "$INSTALL" | grep -qv 'echo\|say\|warn'; then
  bad "G10 the script still builds a PKCS#12" "an empty passphrase fails macOS's MAC check and a real one can only reach 'security import' on argv"
else
  ok "G10 no PKCS#12 is built, so no passphrase has to travel anywhere"
fi

echo ""
echo "=== Z. this suite touched nothing of the operator's ==="
REAL_IDS_AFTER="$(security find-identity -v -p codesigning 2>/dev/null || true)"
if [ "$REAL_IDS_AFTER" = "$REAL_IDS_BEFORE" ]; then
  ok "Z the real keychain's codesigning inventory is identical before and after"
else
  bad "Z THE SUITE CHANGED THE REAL KEYCHAIN" "before='$REAL_IDS_BEFORE' after='$REAL_IDS_AFTER'"
fi

echo ""
if [ "$FAIL" -gt 0 ]; then
  echo "=== signing-setup tests: $FAIL FAILED, $PASS passed ==="
  exit 1
fi
echo "=== signing-setup tests: all $PASS passed ==="
