#!/usr/bin/env bash
#
# signing-setup.test.sh — make-signing-csr.sh and install-signing-cert.sh.
#
# ONE SUITE FOR TWO SCRIPTS, deliberately. The certificate installer's fixtures
# ARE the CSR script's outputs: a key it generated, and certificates signed by that
# key. Splitting them would mean one suite re-deriving the other's artefacts with
# openssl by hand, which is a second implementation of the thing under test.
#
# WHAT IS REAL HERE AND WHAT IS NOT. The keys, CSRs and certificates below are
# real: generated by the real openssl, and the modulus and certificate-type checks
# run against them. What is NOT real is Apple — every certificate here is
# self-signed, because there is no Developer ID certificate on this machine or any
# other machine in this project. Case F6 therefore reaches the keychain import
# behind a `security` SHIM, and case Z proves the operator's real keychain was
# never touched by any case. A suite that installed a self-signed certificate
# calling itself "Developer ID Application" into somebody's login keychain would be
# a worse defect than the one it was testing for.
#
# Cases:
#   E1  a key directory inside a git worktree is REFUSED
#   E2  the generated key is RSA 2048, the CSR is SHA-256, modes are 600/700
#   E3  a second run does not overwrite an existing key
#   E4  ...and --force does, which is what makes E3 mean something
#   E5  a country code that is not two upper-case letters is refused
#   E6  --show on an empty directory says ABSENT rather than inventing a state
#   E7  --show reports the subject of a CSR that exists
#   F1  no argument -> refuse
#   F2  a .cer that does not exist -> refuse
#   F3  the private key missing -> refuse, and say why a .cer alone is useless
#   F4  a certificate issued against a DIFFERENT key -> refuse on the modulus
#   F5  a certificate that is not "Developer ID Application" -> refuse, by name
#   F6  [shim] the matching, correctly-typed certificate reaches "installed and usable"
#   F7  [shim] ...and the Team ID is read out of the identity string
#   F8  ...and the passphrase-less PKCS#12 does not survive the import
#   F9  [shim] an import that reports success and yields NO identity is a FAILURE
#   Z   the operator's real keychain inventory is unchanged by this suite
set -uo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CSR="$SRC_DIR/make-signing-csr.sh"
INSTALL="$SRC_DIR/install-signing-cert.sh"

TMP="$(mktemp -d -t signing-setup-test.XXXXXX)"
trap 'rm -rf "$TMP"' EXIT
REAL_IDS_BEFORE="$(security find-identity -v -p codesigning 2>/dev/null || true)"

PASS=0; FAIL=0
ok()  { printf '  PASS  %s\n' "$1"; PASS=$((PASS + 1)); }
bad() { printf '  FAIL  %s\n         %s\n' "$1" "${2:-}"; FAIL=$((FAIL + 1)); }
run() { OUT="$("$@" 2>&1)"; CODE=$?; return 0; }
expect() {
  local name="$1" want="$2" needle="$3"
  if [ "$CODE" != "$want" ]; then
    bad "$name" "exit $CODE, wanted $want. Output: $(printf '%s' "$OUT" | tr '\n' ' ' | cut -c1-200)"
  elif ! printf '%s' "$OUT" | grep -Fq -- "$needle"; then
    bad "$name" "exit $want as wanted, but the output never said '$needle'"
  else ok "$name"; fi
}

SHIM="$TMP/shim"; mkdir -p "$SHIM"
cat > "$SHIM/security" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  find-identity)
    echo '  1) DEADBEEF0001 "Developer ID Application: Test Person (TEAM00001)"'
    echo '     1 valid identities found' ;;
  find-certificate) exit 0 ;;
  import)           echo "1 key imported."; echo "1 certificate imported." ;;
  *) exit 1 ;;
esac
exit 0
EOF
chmod +x "$SHIM/security"

echo ""
echo "=== E. make-signing-csr.sh ==="
REPO="$TMP/repo"; mkdir -p "$REPO"; git -C "$REPO" init -q 2>/dev/null
run bash "$CSR" --dir "$REPO/keys" --name "Test Person" --email t@example.com --country GB
expect "E1 a key directory inside a git worktree is refused" 2 "is inside a git worktree"

D="$TMP/keys"
run bash "$CSR" --dir "$D" --name "Test Person" --email t@example.com --country GB
if [ "$CODE" != 0 ]; then
  bad "E2 generation" "exit $CODE: $OUT"
else
  bits="$(openssl rsa -in "$D/developer-id.key" -noout -text 2>/dev/null | sed -n 's/^.*Private-Key: (\([0-9]*\) bit.*/\1/p' | head -1)"
  alg="$(openssl req -in "$D/developer-id.certSigningRequest" -noout -text | sed -n 's/^ *Signature Algorithm: *//p' | head -1)"
  kmode="$(stat -f '%Lp' "$D/developer-id.key")"; dmode="$(stat -f '%Lp' "$D")"
  if [ "$bits" = 2048 ] && [ "$alg" = "sha256WithRSAEncryption" ] && [ "$kmode" = 600 ] && [ "$dmode" = 700 ]; then
    ok "E2 RSA $bits, $alg, key mode $kmode in a $dmode directory"
  else
    bad "E2 the generated material is not what Apple's Certificate Assistant emits" \
        "bits=$bits alg=$alg key=$kmode dir=$dmode"
  fi
fi

KEY_BEFORE="$(shasum -a 256 "$D/developer-id.key" | cut -d' ' -f1)"
run bash "$CSR" --dir "$D" --name "Test Person" --email t@example.com --country GB
KEY_AFTER="$(shasum -a 256 "$D/developer-id.key" | cut -d' ' -f1)"
if [ "$CODE" = 2 ] && [ "$KEY_BEFORE" = "$KEY_AFTER" ]; then
  ok "E3 a second run refuses and leaves the existing key byte-identical"
else
  bad "E3 an existing key was not protected" "exit $CODE, key changed: $([ "$KEY_BEFORE" != "$KEY_AFTER" ] && echo yes || echo no)"
fi

run bash "$CSR" --dir "$D" --name "Test Person" --email t@example.com --country GB --force
if [ "$CODE" = 0 ] && [ "$(shasum -a 256 "$D/developer-id.key" | cut -d' ' -f1)" != "$KEY_BEFORE" ]; then
  ok "E4 --force does overwrite, so E3's refusal is a decision and not an inability"
else
  bad "E4 --force did not overwrite" "exit $CODE"
fi

run bash "$CSR" --dir "$TMP/k2" --name "Test Person" --email t@example.com --country gb
expect "E5 a country code that is not two upper-case letters is refused" 2 "two-letter country code"

run bash "$CSR" --dir "$TMP/never" --show
expect "E6 --show on an empty directory says so rather than inventing a state" 0 "does not exist"
run bash "$CSR" --dir "$D" --show
expect "E7 --show reports the subject of the CSR that exists" 0 "CN=Test Person"

echo ""
echo "=== F. install-signing-cert.sh ==="
run bash "$INSTALL"
expect "F1 no argument -> refuse" 2 "give me the .cer Apple issued"
run bash "$INSTALL" --dir "$D" "$TMP/nope.cer"
expect "F2 a .cer that does not exist -> refuse" 2 "no such file"

mkdir -p "$TMP/keyless"
run bash "$INSTALL" --dir "$TMP/keyless" "$D/developer-id.certSigningRequest"
expect "F3 no private key -> refuse, and say why a .cer alone is useless" 2 "cannot sign anything"

# A certificate from a DIFFERENT key, self-signed, DER — the shape Apple sends.
openssl req -x509 -newkey rsa:2048 -nodes -sha256 -days 2 \
  -keyout "$TMP/other.key" -out "$TMP/other.pem" \
  -subj "/CN=Developer ID Application: Test Person (TEAM00001)" >/dev/null 2>&1
openssl x509 -in "$TMP/other.pem" -outform DER -out "$TMP/other.cer" 2>/dev/null
run bash "$INSTALL" --dir "$D" "$TMP/other.cer"
expect "F4 a certificate issued against a different key -> refuse on the modulus" 2 "public moduli differ"

# The RIGHT key, the WRONG type.
openssl req -new -key "$D/developer-id.key" -sha256 -out "$TMP/wrong.csr" \
  -subj "/CN=Developer ID Installer: Test Person (TEAM00001)" >/dev/null 2>&1
openssl x509 -req -in "$TMP/wrong.csr" -signkey "$D/developer-id.key" -days 2 -sha256 \
  -outform DER -out "$TMP/wrong.cer" >/dev/null 2>&1
run bash "$INSTALL" --dir "$D" "$TMP/wrong.cer"
expect "F5 a Developer ID INSTALLER certificate is refused, by name" 2 "signs .pkg installers only"

# The RIGHT key and the RIGHT type.
openssl req -new -key "$D/developer-id.key" -sha256 -out "$TMP/right.csr" \
  -subj "/CN=Developer ID Application: Test Person (TEAM00001)" >/dev/null 2>&1
openssl x509 -req -in "$TMP/right.csr" -signkey "$D/developer-id.key" -days 2 -sha256 \
  -outform DER -out "$TMP/right.cer" >/dev/null 2>&1
run env PATH="$SHIM:$PATH" bash "$INSTALL" --dir "$D" "$TMP/right.cer"
expect "F6 [shim] the matching, correctly-typed certificate reaches 'installed and usable'" 0 "is installed and usable"
if printf '%s' "$OUT" | grep -Fq "Team ID: TEAM00001"; then
  ok "F7 [shim] ...and the Team ID is read out of the identity string"
else
  bad "F7 the Team ID was not extracted" "$(printf '%s' "$OUT" | tr '\n' ' ' | cut -c1-200)"
fi
if [ -f "$D/developer-id.p12" ]; then
  bad "F8 the unencrypted PKCS#12 was left on disk" "$D/developer-id.p12 still exists"
else
  ok "F8 the passphrase-less PKCS#12 was removed after the import"
fi

# F9 — THE FAILURE THIS SCRIPT WAS WRITTEN FOR. `security import` reporting success
# and no identity resulting is the state that reads like the certificate failed and
# is actually a key/keychain mismatch. Without this case the branch that catches it
# is unreachable in the suite, which was proven: mutation N15 disarmed it and
# nothing went red.
SHIM0="$TMP/shim0"; mkdir -p "$SHIM0"
cat > "$SHIM0/security" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  find-identity)    echo '     0 valid identities found' ;;
  find-certificate) exit 0 ;;
  import)           echo "1 key imported." ;;
  *) exit 1 ;;
esac
exit 0
EOF
chmod +x "$SHIM0/security"
run env PATH="$SHIM0:$PATH" bash "$INSTALL" --dir "$D" "$TMP/right.cer"
expect "F9 [shim] an import that reports success but yields NO identity is a FAILURE" 1 "the import reported success and NO Developer ID Application identity exists"

echo ""
echo "=== Z. this suite touched nothing of the operator's ==="
REAL_IDS_AFTER="$(security find-identity -v -p codesigning 2>/dev/null || true)"
if [ "$REAL_IDS_AFTER" = "$REAL_IDS_BEFORE" ]; then
  ok "Z the real keychain's codesigning inventory is identical before and after"
else
  bad "Z THE SUITE CHANGED THE REAL KEYCHAIN" "before='$REAL_IDS_BEFORE' after='$REAL_IDS_AFTER'"
fi

echo ""
if [ "$FAIL" -gt 0 ]; then
  echo "=== signing-setup tests: $FAIL FAILED, $PASS passed ==="
  exit 1
fi
echo "=== signing-setup tests: all $PASS passed ==="
